<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_consultations').toggle(true);
$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
dep_menu_consultation1();
$('#menu_consultations_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>

<?php use Consultation\View\Helper\DateHelper; ?>
<?php $Control = new DateHelper(); ?>

<!-- LES SCRIPS DES PLUGINS ET DES JS -->
<?php 
  echo $this->headLink()->appendStylesheet($this->basePath().'/css/pikachoose/bottom.css');
  echo  $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.jcarousel.min.js');
  echo  $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.pikachoose.min.js');
  
  echo $this->headScript()->appendFile($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.js');
  echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.css');
  
  echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.css');
  echo $this->headScript()->appendFile($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.js');
    
  echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsConsulter.js');
?>

<!-- LES SCRIPS CSS -->
<?php 
  echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleConsulter.css');
  echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleMonstyle.css');
?>
      


















<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="contenu" >

<?php 
	$form = $this->form;
	$form->setName('AVIS');
	$form->setAttribute('action', $this->url('consultation', array('action'=>'enregistrer-consultation')));
	$form->setAttribute('method', 'post');
	$form->prepare();
	echo $this->form()->openTag($form); ?>

<div id="accordions"> 

	 <!--*************** Accordeon ETAT CIVIL ******************-->
	 <!--*************** Accordeon ETAT CIVIL ******************-->
	 <!--*************** Accordeon ETAT CIVIL ******************-->
	 
	 <!--*1*-->
	 
     <div style='width:160px; font-family: police2;font-size: 17px; font-weight: bold;'>Etat Civil</div>
     <div style='max-height: 340px;'>

       <table style="width: 100%;">
         <tr style="width: 100%;">
         
           <!-- Première colonne photo -->         
           <td style="height: 100px; width: 16%; vertical-align: top;">
             <img id="faces" src='<?php echo $this->basePath().'/images/photos_patients/identite.jpg';?>'  style='float:left; margin-right:40px; width:105px; height:105px;'/>
             <div style=' left: 40px; top: 160px; font-family: time new romans; position: absolute; '> Age: <span style='font-size:19px; font-family: time new romans; color: green; font-weight: bold;'> <?php echo $this->lesdetails['AGE'].' ans'; ?>  </span></div>
                          
           </td> 
           
           
           <!-- Deuxième colonne infos état-civil -->
           <td style="width: 72%;">
           
              <table id="etat_civil" style="width: 100%;">
               <tr style="width: 100%;">
			   	<td style='width:27%; font-family: police1;font-size: 12px;'>
			   		<div ><a style="text-decoration: underline;">Pr&eacute;nom</a><br><p style='font-weight: bold;font-size: 17px;'><?php echo $this->lesdetails['PRENOM'];?></p></div>
			   	</td>

			   	<td style='width:35%; font-family: police1;font-size: 12px;'>
		   		<div ><a style="text-decoration: underline;">Origine g&eacute;ographique</a><br><p style='font-weight: bold;font-size: 17px;'><?php  echo $this->patient->origine_geographique; ?></p></div>
			   	</td>

			    <td style='width:38%; font-family: police1;font-size: 12px;'>
			   		<div ><a style="text-decoration: underline;">T&eacute;l&eacute;phone</a><br><p style='font-weight: bold;font-size: 17px;'><?php echo $this->lesdetails['TELEPHONE'];?></p></div>
			   	</td>

			 </tr>

			 <tr>
			    <td style=' font-family: police1;font-size: 12px;'>
			   		<div ><a style="text-decoration: underline;">Nom</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['NOM'];?></p></div>
			   	</td>

			   	<td style=' font-family: police1;font-size: 12px;'>
			   		<div ><a style="text-decoration: underline;">Statut matrimonial</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['STATUT_MATRIMONIAL']?$this->listeStatutMatrimonial[$this->lesdetails['STATUT_MATRIMONIAL']]:'';?></p></div>
			   	</td>

			   	<td style=' font-family: police1;font-size: 12px;'>
			   		<div ><a style="text-decoration: underline;">Ethnie</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->patient->ethnie?$this->listeEthnies[$this->patient->ethnie]:'';?></p></div>
			   	</td>

			 </tr>

			 <tr>
			    <td style=' font-family: police1;font-size: 12px;'>
			   		
			   		<div ><a style="text-decoration: underline; ">Date de naissance</a><br>
			   		  <p style='font-weight: bold;font-size: 19px;'>
			   		    <?php 
			   		    $date_naissance = $this->lesdetails['DATE_NAISSANCE'];
			   		    if($date_naissance){ echo $Control->convertDate($this->lesdetails['DATE_NAISSANCE']); }else{ echo "";}
			   		    ?> 
			   		  </p>
			   		</div>
			   	
			   	</td>

			    <td style=' font-family: police1;font-size: 12px;'>
			   		<div ><a style="text-decoration: underline;">R&eacute;gime matrimonial</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['REGIME_MATRIMONIAL']?$this->listeRegimeMatrimonial[$this->lesdetails['REGIME_MATRIMONIAL']]:'';?></p></div>
			   	</td>

			   	<td style=' font-family: police1;font-size: 12px;'>
			   		<div ><a style="text-decoration: underline;">Race</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->patient->race;?></p></div>
			   	</td>

			 </tr>

			  <tr>
			   	<td style='width: 27%; font-family: police1;font-size: 12px; vertical-align: top;'>
			   	
			   		<div ><a style="text-decoration: underline;">Sexe</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['SEXE'];?></p></div>
			   		
			   	</td>

			    <td style='display:"block"; font-family: police1;font-size: 12px;'>
			   		<div ><a style="text-decoration: underline;">Adresse</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['ADRESSE'];?></p></div>

			   	</td>
			   	
			   	<td style='display:"block";  font-family: police1;font-size: 12px; vertical-align: top;'>
			   	    <div ><a style="text-decoration: underline;">Profession</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['PROFESSION']?$this->listeProfessions[$this->lesdetails['PROFESSION']]:'';?></p></div>
			   	</td>
			  </tr>
             </table>
           
           </td> 
           
           
           
           <!-- Troisième colonne photo -->
           <td style="width: 12%; vertical-align: top;">
           
             <p style='color: white; opacity: 0.09;'>
               <img id="faces" src='<?php echo $this->basePath().'/images/photos_patients/identite.jpg'?>'  alt="Jonathan Verrecchia" style='float:right; margin-right:15px; width:95px; height:95px;'/>
             </p>
             <span style="position: absolute; right: 63px; top: 150px; color: green; font-family: time new roman; font-size: 17px; "> <?php echo $this->patient->numero_dossier; ?> </span>
             
           </td>
           
         </tr>
         
         
         <!-- Deuxième ligne pour le bas de page -->
         <tr style="width: 100%;">
           <td style="height: 10px; width: 16%;"></td> 
           <td colspan="2"> <div id="barre"></div> </td> 
           
         </tr>
         
         <!-- Troisième ligne pour le bas de page -->
         <tr style="height: 100px; width: 100%;">
           <td style="height: 10px; width: 16%;"></td> 
           
           <td style="width: 72%; vertical-align: top;">
             <table id="numero" style=" padding-top:5px; width: 550px;">
	           <tr style="width: 100%;">
	             <td style="padding-top:5px; width: 70px; font-size: 12px;"> Consultation: </td>
	             <td style="font-weight: bold;"> <?php echo $this->idcons;?></td>
	             <td style="font-weight: bold; width:10px;">|</td>
	             <td style="padding-top:5px; width: 80px; font-size: 12px; "> Date & Heure: </td>
	             <td style="font-weight: bold;"> <?php echo $Control->convertDate($this->date); ?>  -  <?php echo $this->heure;?></td>
	           </tr>
         	 </table>
           </td> 
           
           <td style="width: 12%; vertical-align: top;">
             <div style='color: white; opacity: 1; width:95px; height:40px; float:right'>
               <img  src='<?php echo $this->basePath().'/images_icons/fleur1.jpg'?>'  alt="fleur1" />
             </div>
           </td>
           
         </tr>
       
       
       
       </table>
       
     
       
       
         

     </div>
  
  
     <!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->
     <!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->
     <!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->
     
     <!--*2*-->
     
     <div id='motifsAdmissionConstanteClick' style='font-family: police2;font-size: 17px; font-weight: bold;'>Motifs d'admission et Constantes</div>
     <div style='max-height: 490px;'>
  
     
           <?php echo $this->formHidden($form->get('idpatient'));?>
           <?php echo $this->formHidden($form->get('idmedecin'));?>
           <?php echo $this->formHidden($form->get('idinfirmier'));?>
           <?php echo $this->formHidden($form->get('idadmission'));?>
           <?php echo $this->formHidden($form->get('idcons'));?>
           <?php echo $this->formHidden($form->get('date'));?>
           <?php echo $this->formHidden($form->get('heure'));?>

           <!-- SOUS ACCORDEON MOTIF D'ADMISSION ET CONSTANTES -->
           <div id="accordionsMotifConstantes" style='height: 480px;'>
	           
	           <!--**************** sous accordeon LES MOTIFS D ADMISSIONS ************************-->
	           <!--**************** sous accordeon LES MOTIFS D ADMISSIONS ************************-->
	           <!-- **1** -->
	           <div style='font-family: police2;font-size: 17px; font-weight: bold;'> Motifs d'admission </div>
	           <div>
	           <?php echo  $this->headScript()->appendFile($this->basePath().'/js/consultation/jsAjouterMotifsAdmission.js');?>
	                
	           <div style='width: 100%;'>
	           
		           <table style="width: 100%;">
		             <tr style="width: 100%; height: 340px;">
		             
		                <!-- PREMIERE COLONNE -->
		                <td style="width: 40%; vertical-align: top;">
		                
				            <div style='width: 95%; float: left; '>
		                       <table id="respondeMotif" style='width: 100%;'>
		                          <tr class="form-author" id="motif1">
		                              <th><?php echo $this->formRow($form->get('motif_admission1'));?> <span id="labelSupMotif"> <img class='supprimerMotif1' style='cursor: pointer;' src='../images_icons/sup.png' title='supprimer' /> </span> </th>
		                          </tr>
		                          <tr class="form-author" id="motif2">
		                              <th><?php echo $this->formRow($form->get('motif_admission2'));?> <span id="labelSupMotif"> <img class='supprimerMotif2' style='cursor: pointer;' src='../images_icons/sup.png' title='supprimer' /> </span> </th>
		                          </tr>
		                          <tr class="form-author" id="motif3">
		                              <th><?php echo $this->formRow($form->get('motif_admission3'));?> <span id="labelSupMotif"> <img class='supprimerMotif3' style='cursor: pointer;' src='../images_icons/sup.png' title='supprimer' /> </span> </th>
		                          </tr>
		                          <tr class="form-author" id="motif4">
		                              <th><?php echo $this->formRow($form->get('motif_admission4'));?> <span id="labelSupMotif"> <img class='supprimerMotif4' style='cursor: pointer;' src='../images_icons/sup.png' title='supprimer' /> </span> </th>
		                          </tr>
		                          <tr class="form-author" id="motif5">
		                              <th><?php echo $this->formRow($form->get('motif_admission5'));?> <span id="labelSupMotif"> <img class='supprimerMotif5' style='cursor: pointer;' src='../images_icons/sup.png' title='supprimer' /> </span> </th>
		                          </tr>
		                       </table>
			                       
			                       
		                       <!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
		                       <!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
				               <div id="controls_motifs" style="margin-top: 10px; width: 100%;">
				                  <div style="width: 100%; ">
				                     <div style="width: 10%; height: 1px; float: left; " id="supprimer_donnee">
					                     <img id="supprimer_motif_img" style='margin-left: 5px; cursor: pointer;' src='../images_icons/moin-green.png' title='supprimer' />
					                 </div>
					                 <div style="width: 10%; height: 1px; float: left; " id="ajouter_donnee">
						                 <img id="ajouter_motif_img" style='margin-left: 5px; cursor: pointer;' src='../images_icons/plus-green.png' title='ajouter' />
					                 </div>
				                  </div>
				               </div>
		
				               <!--********************* BOUTON VALIDER-MODIFIER ************************-->
		                       <!--********************* BOUTON VALIDER-MODIFIER ************************-->		            
		                       <table style="width: 80%; position: relative; top: 0px; float: right;">
		                          <tr style="width: 80%;">
		                             <th style="width:65%;">
		                                <div style="float:right;">
		                                     <button id='bouton_motif_valider'>Valider</button>
		                                </div>
		                                <div style="float:right;">
		                                     <button id='bouton_motif_modifier'>Modifier</button>
		                                </div>
		                             </th>
		                          </tr>
		                       </table>
		                       
		                       <script>
		                        var nbMotif = "<?php echo $this->nbMotifs;?>";
		                        cacherToutMotif();
		                        if(nbMotif == 0){ nbMotif = 1; }
		                        afficherMotif(nbMotif);
		                        supprimerUnMotif();
		                       </script>
			                       
			                </div>
		                
		                </td>
		                
		                
		                <!-- DEUXIEME COLONNE -->
	                    <td id="deuxiemeColonne" style="width: 30%; vertical-align: top;"> 
	                    
	                      <table style="width: 100%;">
	                        <tr style="width: 100%; vertical-align: top;" class="designStyleLabel">
	                          
	                          <td id="" style="width: 100%; padding-left: 15px; padding-right: 25px;">
	                          
	                             <label style="width: 100%; height:30px; text-align:left; margin-top: 7px;">
		                           <span style='font-size: 12px;'>&#11166; </span><span>Dur&eacute;e des signes </span> 
		                           <?php echo $this->formRow($form->get('duree_des_signes')); ?> <span style='font-style:italic; font-size: 15px;'>Semaines</span>
		                         </label>
		                         
		                         <label style="width: 100%; height:30px; text-align:left; margin-top: 10px;">
		                           <span style='font-size: 12px;'>&#11166; </span><span>Gravit&eacute;e des signes </span> 
		                           <?php echo $this->formRow($form->get('gravite_des_signes')); ?>
		                         </label>
	                       
	                          </td>
	                          
	                        </tr>
	                      </table>
	                    
	                    </td>

		                <td style="width: 30%; height: 100px; vertical-align: top;">
		                
				            <div style='width: 90%; float: right; margin-right: 10px;'>
			                  <p style='color: white; opacity: 0.5;'>
			                     <img id="faces" src='<?php echo $this->basePath().'/images_icons/donnees_examens_physiques.jpg'?>' style='margin-right:5px; width: 100%; height:300px;'/>
			                  </p>
			                </div>
		                
		                </td>
		                
		             </tr>
		           </table>
		           
	                
	                
               </div>
	                
	                
	           </div>
	           
	           
	           <!--**************** sous accordeon LES CONSTANTES ************************-->
               <!--**************** sous accordeon LES CONSTANTES ************************-->
               <!-- **2** -->
               <div id='constantesClick' style='font-family: police2;font-size: 17px; font-weight: bold;'> Constantes </div>
               <div style="max-height: 250px;">
               
               
               </div>
               
               
	           
           </div>
     
     
     </div>
  
  
     <!-- ******************** Résumé Histoire de la maladie ******************-->
     <!-- ******************** Résumé Histoire de la maladie ******************-->
     <!-- ******************** Résumé Histoire de la maladie ******************--> 
     
     <!--*3*-->
     
     <div style='font-family: police2;font-size: 17px; font-weight: bold;'>R&eacute;sum&eacute; histoire de la maladie</div>  
     <div style=' max-height: 250px;'>
        <table class="styleLabelInputChamps" style="width: 100%;">
          <tr style="width: 100%;">
             <td style="width: 70%;"> <?php echo $this->formRow($form->get('resume_histoire_maladie')); ?> </td>
             <td style="width: 30%;"></td>
          </tr>
        </table>
     </div>
     
     <!-- ********************Antécédents ou Terrain particulier ******************-->
     <!-- ********************Antécédents ou Terrain particulier ******************-->
     <!-- ********************Antécédents ou Terrain particulier ******************--> 
     
     <!--*4*-->
     
     <div style='font-family: police2;font-size: 17px; font-weight: bold;'>Ant&eacute;c&eacute;dents et Historiques</div>  
     <div style='max-height: 500px;'>
  
         <div id="tabsAntecedents">
             <ul>
                <li><a href="#tabss-1">Ant&eacute;c&eacute;dents</a></li>
                <li><a href="#tabss-2">Historiques</a></li>
             </ul>
                                   
	         <div id="tabss-1"> 
	           
		           <!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
		           <!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
		           <!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
		           <table id="MenuTerrainParticulier" style="width:100%;">
		                 <tr style="width:100%;">
		                     <td style="width:50%;">
		                        <div>    
		                            <img class="image1_TP" style='cursor: pointer; position:relative; left: 15%; width: 60%; height: 60%;' src='<?php echo $this->basepath().'/images_icons/antecedentPers2.png'?>' />
		                        </div>
		                     </td>
		                     <td style="width:50%;">
		                        <div>    
		                            <img class="image2_TP" style='cursor: pointer; position:relative; left: 15%; width: 60%; height: 60%;' src='<?php echo $this->basepath().'/images_icons/Antecedentsfam.png'?>' />
		                        </div>
		                     </td>
		                 </tr>
		           </table>
		           
		           <!--****** ================== ANTECEDENTS PERSONNELS ================== ****** -->
		           <!--****** ================== ANTECEDENTS PERSONNELS ================== ****** -->
		           <table id="MenuAntecedentPersonnel" style="width:100%;">
		                <tr style="width:100%;">
		                  <td style="">
		                     <img class="image_fleche" style='cursor: pointer;' src='<?php echo $this->basepath().'/images_icons/flecheg.png'?>' title ="pr&eacute;c&eacute;dent" style=''/>
		                  </td>
		                </tr>
		                <tr style="width:100%;">
		                     <td style="width:25%;">
		                        <div>    
		                            <img class="image1_AP" style='cursor: pointer; width: 100%;' src='<?php echo $this->basepath().'/images_icons/image1c_AP.png'?>' style=''/>
		                        </div>
		                     </td>
		                     <td style="width:25%;">
		                        <div>    
		                            <img class="image4_AP" style='cursor: pointer; width: 100%;' src='<?php echo $this->basepath().'/images_icons/image4c_AP.png'?>' style=''/>
		                        </div>
		                     </td>
		                     <td style="width:25%;">
		                        <div>    
		                            <img class="image2_AP" style='cursor: pointer; width: 100%;' src='<?php echo $this->basepath().'/images_icons/image2c_AP.png'?>' style=''/>
		                        </div>
		                     </td>
		                     <td style="width:25%;">
		                        <div>    
		                            <img class="image3_AP" style='cursor: pointer; width: 100%;' src='<?php echo $this->basepath().'/images_icons/image3c_AP.png'?>' style=''/>
		                        </div>
		                     </td>
		                 </tr>
		           </table>
		           
		           
		           
		           
		           
		           <!--****** ================== CONTENU DIABETIQUE CONNU ================== ****** -->
             	   <!--****** ================== CONTENU DIABETIQUE CONNU ================== ****** -->
                   <table id="ContenuDiabetiqueConnu" style="width:100%; display: none;">
                         
                         <tr style="width:100%;">
                  			 <td colspan="4">
                               <div style="width: 100%; font-family: Tempus Sans ITC;  color: green; font-size: 20px; padding-bottom: 10px;" >&#10049; Les informations diab&eacute;tiques </div>
                  			 </td>
                		 </tr>

                		 <!-- Diabétique connu (oui ou non) -->
                 		 <!-- Diabétique connu (oui ou non) -->

                		 <tr style="width:100%;">
                     		 <td style="width:25%; padding-right: 30px; vertical-align: top;" class="designStyleLabel">
		                         <label style="width: 100%; height:30px; text-align:left; margin-top: 7px; margin-bottom: 7px;">
		                           <span style='font-size: 14px;'>&#10045; </span><span style='font-weight: bold;'>Diab&eacute;tique connu</span> 
		                           <?php echo $this->formRow($form->get('diabetique_connu')); ?> 
		                         </label>
                             </td>
                             <td style="width:75%;"></td>
                         </tr>
                         
                         <tr style="width:100%; display: none;" id="contenuDiabeteConnuSiOui">
                     		 <td style="width:25%; vertical-align: top;" colspan="2" >
                     		   <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                     		     <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 34%;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Type de diab&egrave;te</span> 
		                                    <?php echo $this->formRow($form->get('type_diabetique')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 36%; padding-left: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left; ">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Ann&eacute;e de d&eacute;couverte</span> 
		                                    <?php echo $this->formRow($form->get('annee_decouverte')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 30%; padding-left: 25px;">
                     		           </td>
                     		        
                     		        </tr>
                     		     
                     		        <tr style="width: 100% line-height: 20px;">
                     		           <td style="width: 34%; padding-top: 6px;">
		                           		    <span style='font-size: 19px; padding-left: 15px; font-family: time new roman; font-style: italic;'>
		                           		      Traitement actuel du diab&egrave;te
		                           		    </span> 
                     		           </td>
                     		           <td style="width: 66%;" colspan="2"></td>
                     		        </tr>
                     		     
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td colspan="3">
                     		              
                     		              <table style="width: 100%;">
                     		                 <tr style="width: 100%;">
                     		                 
                     		                    <td style="width: 57%;">
		                     		              <label style="width: 100%; height:30px; text-align:left;">
				                           		    <span style='font-size: 11px;'>&#10148; </span><span>Antidiab&eacute;tique oraux</span> 
				                                    <?php echo $this->formRow($form->get('antidiabetique_oraux')); ?> 
				                                  </label>
		                     		            </td>
		                     		           
		                     		            <td style="width: 43%; padding-left: 25px; padding-right: 25px;">
		                     		              <label style="width: 100%; height:30px; text-align:left; ">
				                           		    <span style='font-size: 11px;'>&#10148; </span><span>Insulinoth&eacute;rapie</span> 
				                                    <?php echo $this->formRow($form->get('insulinotherapie')); ?> 
				                                  </label>
		                     		            </td>
                     		                 
                     		                 </tr>
                     		              </table>
                     		              
                     		              <table style="width: 100%;">
                     		                 <tr style="width: 100%;">
                     		                 
                     		                    <td style="width: 34%;">
		                     		              <label style="width: 100%; height:30px; text-align:left;">
				                           		    <span style='font-size: 11px;'>&#10148; </span><span>R&eacute;gime alimentaire</span> 
				                                    <?php echo $this->formRow($form->get('regime_alimentaire')); ?> 
				                                  </label>
		                     		            </td>
		                     		           
		                     		            <td style="width: 66%; padding-left: 25px; padding-right: 15px;">
		                     		             
		                     		            </td>
                     		                 
                     		                 </tr>
                     		              </table>
                     		              
                     		           </td>
                     		        
                     		        </tr>
                     		     
                     		     </table>
                     		     
                     		   </div>
                     		     
                             </td>
                             
                         </tr>
                         
                         
                         <!-- Antécédents diabète dans la famille (oui ou non) -->
                         <!-- Antécédents diabète dans la famille (oui ou non) -->
                         
                         <tr style="width:100%;">
                     		 <td colspan="2" style="width:100%; padding-right: 30px; vertical-align: top;" >
		                         
		                         <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 38%;">
				                         <label style="width: 100%; height:30px; text-align:left; margin-top: 7px;">
				                           <span style='font-size: 14px;'>&#10045; </span><span style='font-weight: bold;'>Ant&eacute;c&eacute;dents diab&egrave;te dans la famille</span> 
				                           <?php echo $this->formRow($form->get('antecedent_diabete_dans_famille')); ?> 
				                         </label>
				                       </td>
				                       <td style="width: 62%;"></td>
				                       
				                    </tr>
				                 </table>
				                    
                             </td>
                         </tr>
                         
                         
                         <tr style="width:100%;">
                            <td class="TerminerContenuDiabetiqueConnu styleBouton" style='width:100%; padding-bottom: 5px; padding-top: 25px;' colspan="4"> </td>
                         </tr>
	 			   </table> 
	 			   
	 			   
	 			   <!--****** ================== AUTRE TERRAIN CONNU ================== ****** -->
             	   <!--****** ================== AUTRE TERRAIN CONNU ================== ****** -->
                   <table id="ContenuAutreTerrainConnu" style="width:100%; display: none;">
                         
                         <tr style="width:100%;">
                  			 <td colspan="4">
                               <div style="width: 100%; font-family: Tempus Sans ITC;  color: green; font-size: 20px; padding-bottom: 10px;" >&#10049; Autre terrain connu </div>
                  			 </td>
                		 </tr>
                		 
                		 <!-- Autre terrain connu (texte) -->
                         <!-- Autre terrain connu (texte) -->
                         
                         <tr style="width:100%;">
                     		 <td colspan="2" style="width:100%; padding-right: 30px; vertical-align: top;" >
		                         
		                         <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 75%;">
				                         <label style="width: 100%; height:30px; text-align:left; margin-top: 7px; margin-bottom: 7px;">
				                           <span style='font-size: 14px;'>&#10045; </span><span style='font-weight: bold;'>Autre terrain connu</span> 
				                           <?php echo $this->formRow($form->get('autre_terrain_connu')); ?> 
				                         </label>
				                       </td>
				                       <td style="width: 25%;"></td>
				                       
				                    </tr>
				                 </table>
				                    
                             </td>
                         </tr>
                         
                         
                		 <tr style="width:100%;">
                     		 <td colspan="2" style="width:100%; vertical-align: top;" class="zoneContenuObmre">
		                        
                               <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                     		     
                     		     <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td class="colTerrainConnu1" style="width: 15%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>HTA</span> 
		                                    <?php echo $this->formRow($form->get('autres_terrain_connu_hta')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td class="colTraitement1" style="width: 30%; padding-right: 25px; display: none;">
                     		              <label style="width: 100%; height:30px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'>  </span><span>Traitement&nbsp;</span> 
		                                    <?php echo $this->formRow($form->get('hta_traitement')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td class="colDyslipidemie1" style="width: 20%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Dyslipid&eacute;mie</span> 
		                                    <?php echo $this->formRow($form->get('dyslipidemie')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td class="colTraitement2" style="width: 35%;  padding-right: 25px; display: none;">
                     		              <label style="width: 100%; height:30px; padding-right: 10px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'>  </span><span>Traitement&nbsp;</span> 
		                                    <?php echo $this->formRow($form->get('dyslipidemie_traitement')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td class="colPlusTrait1" style="width: 30%; padding-right: 25px;"></td>
                     		           <td class="colPlusTrait2" style="width: 35%; padding-right: 25px;"></td>
                     		        
                     		        </tr>
                                 </table>
                                 
                                 
                                 <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 18%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Ob&eacute;sit&eacute;</span> 
		                                    <?php echo $this->formRow($form->get('obesite')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td class="colTabagisme" style="width: 18%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Tabagisme</span> 
		                                    <?php echo $this->formRow($form->get('tabagisme')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td class="colNbPaquet" style="width: 17%; padding-right: 25px; display: none;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'> </span><span>Nb de PA</span> 
		                                    <?php echo $this->formRow($form->get('tabagisme_nb_paquet')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 15%;">
                     		              <label style="width: 100%; height:30px; padding-right: 10px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Alcool</span> 
		                                    <?php echo $this->formRow($form->get('alcool')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 32%;"></td>
                     		           <td class="colPlusNbPaquet" style="width: 17%; padding-right: 25px;"></td>
                     		        
                     		        </tr>
                                 </table>
                                 
                                 
                                 
                               </div>
                               
                             </td>
                         </tr>
                               
                         
                         
                         <tr style="width:100%;">
                            <td class="TerminerAutreTerrainConnu styleBouton" style='width:100%; padding-bottom: 5px; padding-top: 25px;' colspan="4"> </td>
                         </tr>
                         
                   </table>
                		 
	 			   
	 			   
	 			   
	 			   
	 			   <!--****** ================== ANTECEDENTS MEDICAUX ================== ****** -->
             	   <!--****** ================== ANTECEDENTS MEDICAUX ================== ****** -->
                   <table id="ContenuAntecedentsMedicaux" style="width:100%; display: none;">
                         
                         <tr style="width:100%;">
                  			 <td colspan="4">
                               <div style="width: 100%; font-family: Tempus Sans ITC;  color: green; font-size: 20px; padding-bottom: 10px;" >&#10049; Les ant&eacute;c&eacute;dents m&eacute;dicaux </div>
                  			 </td>
                		 </tr>
                		 
                		 
                     	 <tr style="width: 100%" class="designStyleLabel">
                     		        
                     	   <td style="width: 98%;">
	                         <label style="width: 100%; height:30px; text-align:left; margin-top: 7px; margin-bottom: 7px;">
	                           <span style='font-size: 14px;'>&#10045; </span><span style='font-weight: bold;'>Les ant&eacute;c&eacute;dents notables</span> 
	                           <?php echo $this->formRow($form->get('antecedents_medicaux_notable')); ?> 
	                         </label>
	                       </td>
	                       <td style="width: 2%;"></td>
	                       
	                     </tr>
				                 
                		 
                		 <tr style="width:100%;">
                     		 <td colspan="2" style="width:100%; vertical-align: top;" class="zoneContenuObmre">
		                        
                               <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                     		     
                     		     <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 30%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Anciennes hospitalisations</span> 
		                                    <?php echo $this->formRow($form->get('anciennes_hospitalisations')); ?> 
		                                  </label>
                     		           </td>
                     		        
                     		           <td style="width: 70%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span>Traitements en cours <span style="font-style: italic; font-size: 13px;">(mol&eacute;cules)</span> 
		                                    <?php echo $this->formRow($form->get('traitements_en_cours')); ?> 
		                                  </label>
                     		           </td>
                     		        
                     		        </tr>
                     		        
	 			                 </table>
	 			                 
	 			               </div>
	 			               
	 			             </td>
	 			         </tr>
	 			   
	 			   
	 			   
	 			         <tr style="width:100%;">
                            <td class="TerminerAntecedentsMedicaux styleBouton" style='width:100%; padding-bottom: 5px; padding-top: 25px;' colspan="4"> </td>
                         </tr>
	 			   
	 			   </table>
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   <!--****** ================== ANTECEDENTS CHIRURGICAUX ================== ****** -->
             	   <!--****** ================== ANTECEDENTS CHIRURGICAUX ================== ****** -->
                   <table id="ContenuAntecedentsChirurgicaux" style="width:100%; display: none;">
                         
                         <tr style="width:100%;">
                  			 <td colspan="4">
                               <div style="width: 100%; font-family: Tempus Sans ITC;  color: green; font-size: 20px; padding-bottom: 10px;" >&#10049; Les ant&eacute;c&eacute;dents chirurgicaux </div>
                  			 </td>
                		 </tr>
                		 
                		 
                     	 <tr style="width: 100%" class="designStyleLabel ">
                     		        
                     	   <td style="width: 98%;">
	                         <label style="width: 100%; height:30px; text-align:left; margin-top: 7px; margin-bottom: 7px;">
	                           <span style='font-size: 14px;'>&#10045; </span><span style='font-weight: bold;'>Les ant&eacute;c&eacute;dents notables</span> 
	                           <?php echo $this->formRow($form->get('antecedents_chirurgicaux')); ?> 
	                         </label>
	                       </td>
	                       <td style="width: 2%;"></td>
	                       
	                     </tr>
	 			   
	 			   
	 			   		 <tr style="width:100%;">
                     		 <td colspan="2" style="width:100%; vertical-align: top;" class="zoneContenuObmre">
		                        
                               <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                     		     
                     		     <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 55%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Chirurgie en rapport avec son diab&egrave;te</span> 
		                                    <?php echo $this->formRow($form->get('chirurgie_rapport_avec_diabete')); ?> 
		                                  </label>
                     		           </td>
                     		        
                     		           <td style="width: 45%; padding-right: 25px;">
                     		              <label id="labelChirurgieRapportAvecDiabete" style="width: 100%; height:30px; text-align:left; display: none;">
		                           		    <span style='font-size: 11px;'> </span>  
		                                    <?php echo $this->formRow($form->get('liste_chirurgie_des_membres')); ?> 
		                                  </label>
                     		           </td>
                     		        
                     		        </tr>
                     		        
                     		        
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 55%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Chirurgie sans rapport avec le diab&egrave;te</span> 
		                                    <?php echo $this->formRow($form->get('chirurgie_sans_rapport_avec_diabete')); ?> 
		                                  </label>
                     		           </td>
                     		        
                     		           <td style="width: 45%; padding-right: 25px;">
                     		              <label id="labelChirurgieSansRapportAvecDiabete" style="width: 100%; height:30px; text-align:left; display: none;">
		                           		    <span style='font-size: 11px;'> </span>  
		                                  </label>
                     		           </td>
                     		        
                     		        </tr>
                     		        
                     		        
	 			                 </table>
	 			                 
	 			               </div>
	 			               
	 			             </td>
	 			         </tr>
	 			   
	 			   
	 			   
			 			 <tr style="width:100%;">
                            <td class="TerminerAntecedentsChirurgicaux styleBouton" style='width:100%; padding-bottom: 5px; padding-top: 25px;' colspan="4"> </td>
                         </tr>
	 			   
	 			   </table>
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   
	 			   <!--****** ================== ANTECEDENTS FAMILIAUX ================== ****** -->
		           <!--****** ================== ANTECEDENTS FAMILIAUX ================== ****** -->
		           <table id="MenuAntecedentsFamiliaux" style="width:100%;">
		                <tr style="width:100%;">
		                  <td style="">
		                    <div style="width: 100%; font-family: Tempus Sans ITC;  color: green; font-size: 20px; padding-bottom: 10px;" >&#10049; Les ant&eacute;c&eacute;dents familiaux </div>
                  		  </td>
		                </tr>
		                
		                <tr style="width:100%;">
		                  <td class="TerminerAntecedentsFamiliaux styleBouton" style='width:100%; padding-bottom: 5px; padding-top: 15px;'> </td>
		                </tr>
          		   </table>
	 			   
	 			   
	 			   
	 			   
	 			   <!--****** ================== FIN ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
	               <!--****** ================== FIN ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
	               <!--****** ================== FIN ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
              
	         </div>

	         
	         
	         
	         
	         
	         
	         
             <div id="tabss-2"> 
             
                 <table id="MenuAntecedent" style="width:100%; ">
                   <tr style="width:100%;">
                     <td style="width:25%;">
                        <div>    
                            <img class="image1" style='cursor: pointer; width: 100%; height:200px;' src='<?php echo $this->basepath().'/images_icons/Consultant_logo1.png'?>' />
                        </div>
                     </td>
                     <td style="width:25%;">
                        <div>    
                            <img class="image2" style='cursor: pointer; width: 100%; height:200px;' src='<?php echo $this->basepath().'/images_icons/hospitalisation1.png'?>'  />
                        </div>
                     </td>
                     <td style="width:25%;">
                        <div>    
                            <img class="image3" style='cursor: pointer; width: 100%; height:200px;' src='<?php echo $this->basepath().'/images_icons/examens1.png'?>'  />
                        </div>
                     </td>
                     <td style="width:25%;">
                        <!-- div>    
                            <img class="image4" style='cursor: pointer; width: 100%; height:200px;' src='<?php /* echo $this->basepath().'/images_icons/Autres.jpg'*/ ?>'  />
                        </div-->
                     </td>
                   </tr>
                 </table>
               
               
	             <!-- LISTE DES CONSULTATIONS DU PATIENT -->
	             <!-- LISTE DES CONSULTATIONS DU PATIENT -->
	             <!-- LISTE DES CONSULTATIONS DU PATIENT -->
	             <div id="titreTableauConsultation" style="width: 100%; font-family: Tempus Sans ITC;  color: green; font-size: 20px; padding-bottom: 10px;" >&#10049; Liste des consultations pr&eacute;c&eacute;dentes</div>
	             
	             <div id='ListeCons'>
	             <table class="table table-bordered  tab_list_mini" id="ListeConsultationPatient" style="width:100%;">
				   <thead>
					  <tr style="height:40px; width:100%;">
						<th style="width:25%;" >DATE & HEURE</th>
						<th style="width:35%;" >INFIRMI&Egrave;RE</th>
						<th style="width:35%;" >M&Eacute;DECIN CONSULTANT</th>
						<th style="width:5%;">Voir</th>
					  </tr>
				   </thead>
				  
				  <tbody class="liste_patient">
				    <!-- AFFICHAGE DE LA LISTE DES CONSULTATIONS PRECEDENTES -->
				    <!-- AFFICHAGE DE LA LISTE DES CONSULTATIONS PRECEDENTES -->
				    
				    
				    
	              </tbody>
	             
	             
	             </table>
	             
	             <script> /* historiquesDesConsultations($("#idpatient").val()); */ </script>
	              
	             </div>
	               
	             <table id="boutonTerminerConsultation" style="width:5%;">
	                <tr style="width:100%;">
	                   <td class="TerminerConsultation styleBouton" style='width:100%; padding-bottom: 5px; padding-top: 15px;'> </td>
	                </tr>
	             </table>
	             <!-- FIN LISTE DES CONSULTATIONS DU PATIENT -->
	             <!-- FIN LISTE DES CONSULTATIONS DU PATIENT -->
	             <!-- FIN LISTE DES CONSULTATIONS DU PATIENT -->
               
               
               
               
               
               
	         
	         </div>
	         
	         
	     </div>
  
         <script> setTimeout(function(){ scriptHistoriqueTerrainParticulier(); },900); </script>
  
     </div>
  
  
     <!-- ******************** Examen général ******************-->
     <!-- ******************** Examen général ******************-->
     <!-- ******************** Examen général ******************-->
    
     <!--*4*-->
     <div style='font-family: police2;font-size: 17px; font-weight: bold;' class='ExamenGeneral' >Examen g&eacute;n&eacute;ral</div>
     <div style='max-height: 350px;'>
     
                   <table style="width:100%;" >
                         
	 			   		 <tr style="width:100%;">
                     		 <td  style="width:100%; vertical-align: top;" class="zoneContenuObmre">
		                        
                               <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                     		     
                     		     <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 100%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Etat g&eacute;n&eacute;ral </span> 
		                                    <?php echo $this->formRow($form->get('etat_general')); ?> 
		                                    <span style='font-style: italic; font-size: 17px; font-style: italic; float: right;'> Activit&eacute;&nbsp;  </span>
		                                  </label>
                     		           </td>
                     		        
                     		        </tr>
	 			                 </table>
	 			                 
	 			                 
	 			                 <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		        
                     		           <td style="width: 28%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Muqueuses</span> 
		                                    <?php echo $this->formRow($form->get('muqueuses')); ?> 
		                                  </label>
                     		           </td>
                     		        
                     		           <td style="width: 22%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>D&eacute;shydratation</span> 
		                                    <?php echo $this->formRow($form->get('deshydratation')); ?> 
		                                  </label>
                     		           </td>
                     		        
                     		           <td style="width: 35%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Oed&egrave;me des membres inf&eacute;rieurs</span> 
		                                    <?php echo $this->formRow($form->get('oedeme_membres_inferieurs')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 15%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:left; display: none;">
		                           		    <span style='font-size: 11px;'> </span>  
		                                  </label>
                     		           </td>
                     		           
                     		        </tr>
	 			                 </table>
	 			                 
	 			               </div>
	 			                 
	 			               
	 			             </td>
	 			             
	 			         </tr>
	 			         
	 			         <tr style="width:100%;">  
	 			             <td style="width:100%; vertical-align: top;" class="zoneContenuObmre">
                               <div style="width: 100%; margin-top: 5px; padding: 3px; padding-bottom: 1px;">
	 			             
	 			                 <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 25%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>T.A(mmHG)</span> 
		                           		    <?php echo $this->formRow($form->get('tension_arterielle_max')); ?>
		                                    <?php echo $this->formRow($form->get('tension_arterielle_min')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 14%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'> </span><span>Couch&eacute;&nbsp;</span> 
		                                    <?php echo $this->formRow($form->get('coucheTA')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 14%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'> </span><span>Debout&nbsp;</span> 
		                                    <?php echo $this->formRow($form->get('deboutTA')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 12%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'> </span><span>IPS&nbsp;</span> 
		                                    <?php echo $this->formRow($form->get('ipsTA')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 17%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'> </span><span>Pied gauche&nbsp;</span> 
		                                    <?php echo $this->formRow($form->get('piedgaucheTA')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 18%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'> </span><span>Pied droit&nbsp;</span> 
		                                    <?php echo $this->formRow($form->get('pieddroitTA')); ?> 
		                                  </label>
                     		           </td>
                     		           
                     		        </tr>
                     		     </table>
	 			             
	 			               </div>
	 			             </td>
	 			           </tr>  
	 			           
	 			           
	 			           <tr style="width:100%;">  
	 			             <td style="width:100%; vertical-align: top;" class="zoneContenuObmre">
                               <div style="width: 100%; margin-top: 5px; padding: 3px; padding-bottom: 1px;">
	 			             
	 			                 <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 23%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Pouls (bat./min)</span> 
		                           		    <?php echo $this->formRow($form->get('poulsBatMin')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 37%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Fr&eacute;quence respiratoire (cycles/min)</span> 
		                           		    <?php echo $this->formRow($form->get('frequence_respiratoire_cycles_min')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 22%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Diur&egrave;se horaire</span> 
		                           		    <?php echo $this->formRow($form->get('diurese_horaire')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 18%; padding-right: 23px;"> </td>
                     		           
                     		           
                     		        </tr>
                     		     </table>
                     		     
                     		   </div>
                     	     </td>
                     	   </tr>   
                     	   
                     	   
                     	   <tr style="width:100%;">  
	 			             <td style="width:100%; vertical-align: top;" class="zoneContenuObmre">
                               <div style="width: 100%; margin-top: 5px; padding: 3px; padding-bottom: 1px;">
	 			             
	 			                 <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 18%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Poids (kg)</span> 
		                           		    <?php echo $this->formRow($form->get('poids')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 20%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Taille (cm)</span> 
		                           		    <?php echo $this->formRow($form->get('taille')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 22%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Tour taille (cm)</span> 
		                           		    <?php echo $this->formRow($form->get('tour_taille')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 15%; padding-right: 25px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>IMC</span> 
		                           		    <?php echo $this->formRow($form->get('imc_constante')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 25%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Glyc&eacute;mie capillaire</span> 
		                           		    <?php echo $this->formRow($form->get('glycemie_capillaire')); ?>
		                                  </label>
                     		           </td>
                     	           
                     	            </tr>
                     		     </table>
                     		     
                     		     
                     		     <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 35%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span>Bandelette urinaire <span style="position: absolute;  font-style: italic; left: 27%;">Sucre&nbsp;</span> 
		                           		    <?php echo $this->formRow($form->get('sucre')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 20%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:right;  font-style: italic;">
		                           		    <span style='font-size: 11px;'> </span><span>Corps c&eacute;tonique&nbsp;</span> 
		                           		    <?php echo $this->formRow($form->get('corps_cetonique')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 20%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'> </span><span>Prot&eacute;ines&nbsp;</span> 
		                           		    <?php echo $this->formRow($form->get('proteines')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 20%; padding-right: 15px;">
                     		              <label style="width: 100%; height:30px; text-align:right; font-style: italic;">
		                           		    <span style='font-size: 11px;'> </span><span>H&eacute;maties&nbsp;</span> 
		                           		    <?php echo $this->formRow($form->get('hematies')); ?>
		                                  </label>
                     		           </td>
                     		           
                     		           <td style="width: 5%; padding-right: 15px;"></td>
                     		           
                     		        </tr>   
                     		     </table>
                     		     
                     		     
                     		   </div>
                     	     </td>
                     	   </tr>   
                     	           
                     	           
	 			   
	 			   </table>
     
     </div>
     
     
     
     <!-- ******************** Examen physique ******************-->
     <!-- ******************** Examen physique ******************-->
     <!-- ******************** Examen physique ******************-->
    
     <!--*4*-->
     <div style='font-family: police2;font-size: 17px; font-weight: bold;' class='ExamenGeneral' >Examen physique</div>
     <div style='max-height: 500px;'>
     
                   <table style="width:100%;" class="champsAjoutAppareilSysteme champsAjoutAppareilSysteme_1">
                         
                         <tr style="width: 100%" class="designStyleLabel RadiusLabel">
                     	   <td style="width: 59%;">
	                         <label style="width: 98%; height:30px; text-align:left; margin-bottom: 7px;" class="champInputAppSys_1" >
	                           <span style='font-size: 14px;'>&#10045; </span><span style='font-weight: bold; font-style: italic;'>Appareil d'appel ou syst&egrave;me - 1 </span> 
	                           <?php echo $this->formRow($form->get('appareil_appel_systeme_1')); ?>
	                           <input type="hidden" id="valueChampInputAppSysSelect_1">
	                           
	                         </label>
	                       </td>
	                       
	                       <td rowspan="2" style="width:41%; vertical-align: top;">
	 			               <div style="width: 95%; padding: 3px; padding-bottom: 1px; margin-left: 22px; display: none;" class="examenPhysiqueInfos1 zoneContenuObmrePikaImg">
                     		     <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 20%; padding-right: 23px; vertical-align: top;">
                     		              <label style="width: 100%; height:15px; text-align:left; line-height: 0.7em;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Iconographie</span> 
		                                  </label>
                     		           </td>
                     		           
                     		           <td rowspan="2" style="width: 80%; padding-right: 23px;" id="zonePikaImage1">
                     		           
                     		               <!-- PIKACHOOSE -->
                                           <!-- PIKACHOOSE -->
                                           <div id="pika" style="margin-top: 5px; margin-bottom: -15px;">
                                             <div id="pika2" align="center">
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                                <!-- EMPLACEMENT DES IMAGES -->
                                             </div>
                                           </div>
                                           <div id="AjoutImage" style="position: relative; bottom: 25px; left: 15px; float: right;">
                                                  <input type='file' name="fichier" />
			                                      <!-- RECUPERER L'IMAGE -->
			                                      <input type='hidden' id="fichier_tmp" name="fichier_tmp" />
			                                      <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
                                           </div>
                     		           
                     		               <script> setTimeout(function(){ $("#zonePikaImage1").hover(function(){ temoinSupprImagePika2 = 1;}); }); </script>
                                             
                     		           </td>
                     		        </tr>
                     		        
                     		        <tr style="width: 100%; height: 197px;">
                     		           <td style="width: 20%; padding-right: 23px;" id="imageWaiting"></td>
                     		        </tr>
                     		        
                    		     </table>
                     		   
                     		     <!-- POP UP pour Confirmation Suppression -->
				                 <div id="confirmation" title="Confirmation de la suppression" style="display:none;">
				                   <p style="font-size: 14px;">
				                      <span style="float:left; margin:0 0px 20px 0; ">
				                      <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
				                      Etes-vous s&ucirc;r de vouloir supprimer l'image n&deg;<span id="nbImgPosAppSys1"> </span> <br> (Appareil ou systeme - 1) ?</span>
				                   </p>
				                 </div>
                 
                 
                     		     <script type="text/javascript">getimagesExamensMorphologiques();</script>
                     		   </div>
	 			             </td>
	                     </tr>
                         
	 			   		 <tr style="width:100%;">
                     		 <td style="width:59%; vertical-align: top;" class="zoneContenuObmre">
		                        
                               <div style="width: 100%; padding: 3px; padding-bottom: 1px; display: none;" class="examenPhysiqueInfos1">
                     		     
                     		     <table style="width: 100%;" >
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 100%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Inspection </span> 
		                                    <input  type='Text' style='float:right; width: 80%; height: 28px; font-family: time new roman; font-size: 19px; padding-left: 3px; margin-top: 2px;'> 
		                                  </label>
                     		           </td>
                     		        </tr>
                     		        
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 100%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Palpitation  </span> 
		                                    <input  type='Text' style='float:right; width: 80%; height: 28px; font-family: time new roman; font-size: 19px; padding-left: 3px; margin-top: 2px;'> 
		                                  </label>
                     		           </td>
                     		        </tr>
                     		        
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 100%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Percussion   </span> 
		                                    <input  type='Text' style='float:right; width: 80%; height: 28px; font-family: time new roman; font-size: 19px; padding-left: 3px; margin-top: 2px;'> 
		                                  </label>
                     		           </td>
                     		        </tr>
                     		        
                     		        <tr style="width: 100%" class="designStyleLabel">
                     		           <td style="width: 100%; padding-right: 23px;">
                     		              <label style="width: 100%; height:30px; text-align:left;">
		                           		    <span style='font-size: 11px;'>&#10148; </span><span>Auscultation    </span> 
		                                    <input  type='Text' style='float:right; width: 80%; height: 28px; font-family: time new roman; font-size: 19px; padding-left: 3px; margin-top: 2px;'> 
		                                  </label>
                     		           </td>
                     		        </tr>
                     		        
	 			                 </table>
	 			                 
	 			               </div>
	 			               
	 			             </td>
	 			             
	 			             
	 			         </tr>
	 			   
	 			   </table>
	 			   
	 			   
	 			   
	 			   <table style="width:100%;" >
                      <tr style="width: 100%">
                         <td style="width: 20%;">
	 			           <div id='examen_physique_moins' class='examen_physique_pm' onclick='enleverExamenPhysiqueAppareilSysteme();'> &minus; </div> 
	 			           <div id='examen_physique_plus' class='examen_physique_pm' onclick='ajouterExamenPhysiqueAppareilSysteme();' style='display: none;'> + </div>
	 			         </td>
	 			         <td style="width: 80%;" ></td>
	 			      </tr>
	 			   </table>
     
     </div>
     
     
     
     <!-- ******************** Examens biologiques ******************-->
     <!-- ******************** Examens biologiques ******************-->
     <!-- ******************** Examens biologiques ******************-->
    
     <!--*4*-->
     <div style='font-family: police2;font-size: 17px; font-weight: bold;' >Examens biologiques</div>
     <div style='max-height: 300px;'>
     
        <table style="width:100%;" >
                         
           <tr style="width: 100%" >
              <td style="width: 59%; vertical-align: top;" class="zoneContenuObmre" >
                 <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                     		     
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabel">
                     		        
                     	     <td style="width: 35%; padding-right: 25px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>Glyc&eacute;mie &agrave; jeun </span> 
		                            <?php echo $this->formRow($form->get('glycemie_jeun')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 35%; padding-right: 25px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='H&eacute;moglobine glyqu&eacute;e'>H&eacute;mo. glyqu&eacute;e </span> 
		                            <?php echo $this->formRow($form->get('hemoglobine_glyquee')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 30%; padding-right: 23px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='Cr&eacute;atinin&eacute;mie'>Cr&eacute;at. </span> 
		                            <?php echo $this->formRow($form->get('creatininemie')); ?> 
		                        </label>
                     		 </td>
                          </tr>
	 			       </table>
	 			       
	 			       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabel">
                     		        
                     	     <td style="width: 35%; padding-right: 25px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>GSRh </span> 
		                            <?php echo $this->formRow($form->get('grsh')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 35%; padding-right: 25px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>TP</span> 
		                            <?php echo $this->formRow($form->get('tp')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 30%; padding-right: 23px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span >TCA </span> 
		                            <?php echo $this->formRow($form->get('tca')); ?> 
		                        </label>
                     		 </td>
                          </tr>
	 			       </table>
	 			       
	 			       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabel">
                     		        
                     	     <td style="width: 35%; padding-right: 25px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>HDL-C </span> 
		                            <?php echo $this->formRow($form->get('hdl_c')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 35%; padding-right: 25px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>LDL-C</span> 
		                            <?php echo $this->formRow($form->get('ldl_c')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 30%; padding-right: 23px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span >Uric&eacute;mie </span> 
		                            <?php echo $this->formRow($form->get('uricemie')); ?> 
		                        </label>
                     		 </td>
                          </tr>
	 			       </table>
	 			       
	 			       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabel">
                     		        
                     	     <td style="width: 35%; padding-right: 25px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>Triglyc&eacute;rides </span> 
		                            <?php echo $this->formRow($form->get('triglycerides')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 35%; padding-right: 25px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title="Microalbuminurie/PU24h">Mic. alb./PU24h</span> 
		                            <?php echo $this->formRow($form->get('microalbuminurie_pu24h')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 30%; padding-right: 23px;"></td>
                          </tr>
	 			       </table>
	 			       
     
                 </div>
              </td>

              <td style="width:41%; vertical-align: top;">
     
                 <div style="width: 95%; padding: 3px; padding-bottom: 1px; margin-left: 22px; " class="zoneContenuObmrePikaImg">
                    
                    <table style="width: 100%;" >
                      <tr style="width: 100%;" class="designStyleLabel">
                        <td style="width: 20%; padding-right: 23px; vertical-align: top;">
                     	   <label style="width: 100%; height:15px; text-align:left; line-height: 0.7em;">
		                     <span style='font-size: 11px;'>&#10148; </span><span>H&eacute;mogramme</span> 
		                   </label>
                     	</td>
                     		           
                     	<td  rowspan="2" style="width: 80%; padding-right: 23px; vertical-align: top;" id="zonePikaImageNfs">
                     		    
                     		           
	                     	<!-- PIKACHOOSE -->
	                        <!-- PIKACHOOSE -->
	                        <div id="pikaNfs" style=" width: 100%; margin-top: 5px; margin-bottom: -15px;">
	                          <div id="pika2Nfs" align="center">
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <div class="pikachoose" style="height: 210px;">
		                           <ul id="pikameNfs" class="jcarousel-skin-pika"></ul>
		                        </div>
	                          </div>
	                        </div>
	                        <div id="AjoutImageNfs"  class="AjoutImage" style="position: relative; bottom: 25px; left: 15px; float: right;">
	                           <input type='file' name="fichier">
				               <!-- RECUPERER L'IMAGE -->
				               <input type='hidden' id="fichier_tmpNfs" name="fichier_tmpNfs" />
				               <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
	                        </div>
	                     		  
	                        <script type="text/javascript"> setTimeout(function(){ scriptPikameChooseOther('Nfs'); }); </script>      
                     		<script type="text/javascript"> setTimeout(function(){ scriptAddImageInDataBaseOther('Nfs'); }); </script>
                     		<script type="text/javascript"> setTimeout(function(){ $("#zonePikaImageNfs").hover(function(){ temoinSupprImagePika2 = 50;}); }); </script>
                            <script type="text/javascript"> setTimeout(function(){ getImagesExamensOther('Nfs'); });</script>        
                                                  
                     	</td>
                     	
                      </tr>
                     		        
                      <tr style="width: 100%; height: 197px;">
                     	 <td style="width: 20%; padding-right: 23px;" id="imageWaitingNfs"></td>
                      </tr>
                     		        
                   </table>
                    
                 </div>
                     		   
                   <!-- POP UP pour Confirmation Suppression -->
				   <div id="confirmationNfs" title="Confirmation de la suppression" style="display:none;">
				     <p style="font-size: 14px;">
				       <span style="float:left; margin:0 0px 20px 0; ">
				         <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
				         Etes-vous s&ucirc;r de vouloir supprimer l'image n&deg;<span id="nbImagesPositionPopupNfs"> </span>
				       </span>
				     </p>
				   </div>                  
     
     		  </td>
           </tr>
           
        
        </table>
     
     </div>
     
     
     
     <!-- ******************** Examens fonctionnels ******************-->
     <!-- ******************** Examens fonctionnels ******************-->
     <!-- ******************** Examens fonctionnels ******************-->
    
     <!--*8*-->
     <div style='font-family: police2;font-size: 17px; font-weight: bold;' >Examens fonctionnels</div>
     <div style='max-height: 300px;'>
     
        <table style="width:100%;" >
                         
           <tr style="width: 100%" >
              <td style="width: 59%; vertical-align: top;" class="zoneContenuObmre" >

                 <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabelTextarea">
                     	     <td style="width: 35%; padding-right: 23px;">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>ECG </span> 
		                            <?php echo $this->formRow($form->get('ecg')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
                 <div style="width: 60%; padding: 3px; padding-bottom: 1px; margin-top: 5px;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabel">
                     	     <td style="width: 100%; padding-right: 23px;">
                     		    <label style="width: 100%; height:30px; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>Indice de pression systolique </span> 
		                            <?php echo $this->formRow($form->get('indice_pression_systolique')); ?> 
		                        </label>
                     		 </td>
                          </tr>
                       </table>
                 </div>
                 
              </td>

              <td style="width:41%; vertical-align: top;">
     
                 <div style="width: 95%; padding: 3px; padding-bottom: 1px; margin-left: 22px; " class="zoneContenuObmrePikaImg">
                    
                    <table style="width: 100%;" >
                      <tr style="width: 100%;" class="designStyleLabel">
                        <td style="width: 20%; padding-right: 23px; vertical-align: top;">
                     	   <label style="width: 100%; height:15px; margin-right: 60px; text-align:left; line-height: 0.7em;">
		                     <span style='font-size: 11px;'>&#10148; </span><span>ECG</span> 
		                   </label>
                     	</td>
                     		           
                     	<td  rowspan="2" style="width: 80%; padding-right: 23px; vertical-align: top;" id="zonePikaImageEcg">
                     	
                     	
                     	
                     	    <!-- PIKACHOOSE -->
	                        <!-- PIKACHOOSE -->
	                        <div id="pikaEcg" style=" width: 100%; margin-top: 5px; margin-bottom: -15px;">
	                          <div id="pika2Ecg" align="center">
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <div class="pikachoose" style="height: 210px;">
		                           <ul id="pikameEcg" class="jcarousel-skin-pika"></ul>
		                        </div>
	                          </div>
	                        </div>
	                        <div id="AjoutImageEcg"  class="AjoutImage" style="position: relative; bottom: 25px; left: 15px; float: right;">
	                           <input type='file' name="fichier">
				               <!-- RECUPERER L'IMAGE -->
				               <input type='hidden' id="fichier_tmpEcg" name="fichier_tmpEcg" />
				               <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
	                        </div>
	                     		  
	                        <script type="text/javascript"> setTimeout(function(){ scriptPikameChooseOther('Ecg'); }); </script>      
                     		<script type="text/javascript"> setTimeout(function(){ scriptAddImageInDataBaseOther('Ecg'); }); </script>
                     		<script type="text/javascript"> setTimeout(function(){ $("#zonePikaImageEcg").hover(function(){ temoinSupprImagePika2 = 51;}); }); </script>
                            <script type="text/javascript"> setTimeout(function(){ getImagesExamensOther('Ecg'); });</script>        
                     	
                     	</td>
                     	
                      </tr>
                      
                      <tr style="width: 100%; height: 197px;">
                     	 <td style="width: 20%; padding-right: 23px;" id="imageWaitingEcg"></td>
                      </tr>
                      
                      
                    </table>
     
                 </div>
                 
                 <!-- POP UP pour Confirmation Suppression -->
			     <div id="confirmationEcg" title="Confirmation de la suppression" style="display:none;">
			       <p style="font-size: 14px;">
			         <span style="float:left; margin:0 0px 20px 0; ">
			           <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
			           Etes-vous s&ucirc;r de vouloir supprimer l'image n&deg;<span id="nbImagesPositionPopupEcg"> </span>
			         </span>
			       </p>
			     </div> 
				   
     
              </td>
           </tr>
              
        </table>
              
     </div>
         
         
         
     <!-- ******************** Examens radiologiques ******************-->
     <!-- ******************** Examens radiologiques ******************-->
     <!-- ******************** Examens radiologiques ******************-->
    
     <!--*9*-->
     <div style='font-family: police2;font-size: 17px; font-weight: bold;' >Examens radiologiques</div>
     <div style='max-height: 500px;'>
     
        <table style="width:100%;" >
                         
           <tr style="width: 100%" >
              <td style="width: 59%; vertical-align: top;" class="zoneContenuObmre" >

                 <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabelTextarea">
                     	     <td style="width: 35%; padding-right: 23px;">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='Radiographie standard 1'>Radio 1. </span> 
		                            <?php echo $this->formRow($form->get('rsd1')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
                 <div style="width: 100%; padding: 3px; margin-top: 10px; padding-bottom: 1px;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabelTextarea">
                     	     <td style="width: 35%; padding-right: 23px;">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='Radiographie standard 2'>Radio 2. </span> 
		                            <?php echo $this->formRow($form->get('rsd2')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
              </td>

              <td style="width:41%; vertical-align: top;">
     
                 <div style="width: 95%; padding: 3px; padding-bottom: 1px; margin-left: 22px; " class="zoneContenuObmrePikaImg">
                    
                    <table style="width: 100%;" >
                      <tr style="width: 100%;" class="designStyleLabel">
                        <td style="width: 20%; padding-right: 23px; vertical-align: top;">
                     	   <label style="width: 100%; height:15px; text-align:left; line-height: 0.7em;">
		                     <span style='font-size: 11px;'>&#10148; </span><span title='Radiographie standard'>Radiograhie.</span> 
		                   </label>
                     	</td>
                     		           
                     	<td  rowspan="2" style="width: 80%; padding-right: 23px; vertical-align: top;" id="zonePikaImageRsd">
                     	
                     	
                     	
                     	    <!-- PIKACHOOSE -->
	                        <!-- PIKACHOOSE -->
	                        <div id="pikaRsd" style=" width: 100%; margin-top: 5px; margin-bottom: -15px;">
	                          <div id="pika2Rsd" align="center">
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <div class="pikachoose" style="height: 210px;">
		                           <ul id="pikameRsd" class="jcarousel-skin-pika"></ul>
		                        </div>
	                          </div>
	                        </div>
	                        <div id="AjoutImageRsd"  class="AjoutImage" style="position: relative; bottom: 25px; left: 15px; float: right;">
	                           <input type='file' name="fichier">
				               <!-- RECUPERER L'IMAGE -->
				               <input type='hidden' id="fichier_tmpRsd" name="fichier_tmpRsd" />
				               <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
	                        </div>
	                     		  
	                        <script type="text/javascript"> setTimeout(function(){ scriptPikameChooseOther('Rsd'); }); </script>      
                     		<script type="text/javascript"> setTimeout(function(){ scriptAddImageInDataBaseOther('Rsd'); }); </script>
                     		<script type="text/javascript"> setTimeout(function(){ $("#zonePikaImageRsd").hover(function(){ temoinSupprImagePika2 = 52;}); }); </script>
                            <script type="text/javascript"> setTimeout(function(){ getImagesExamensOther('Rsd'); });</script>        
                     	
                     	</td>
                     	
                      </tr>
                      
                      <tr style="width: 100%; height: 197px;">
                     	 <td style="width: 20%; padding-right: 23px;" id="imageWaitingRsd"></td>
                      </tr>
                      
                      
                    </table>
                   
     
                 </div>
                 
                 <!-- POP UP pour Confirmation Suppression -->
			     <div id="confirmationRsd" title="Confirmation de la suppression" style="display:none;">
			       <p style="font-size: 14px;">
			         <span style="float:left; margin:0 0px 20px 0; ">
			           <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
			           Etes-vous s&ucirc;r de vouloir supprimer l'image n&deg;<span id="nbImagesPositionPopupRsd"> </span>
			         </span>
			       </p>
			     </div> 
				   
     
              </td>
           </tr>
              
        </table>
        
        
        <table style="width:100%; margin-top: 6px;" >
                         
           <tr style="width: 100%" >
              <td style="width: 59%; vertical-align: top;" class="zoneContenuObmre" >

                 <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabelTextarea">
                     	     <td style="width: 35%; padding-right: 23px;">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>Scanner </span> 
		                            <?php echo $this->formRow($form->get('scanner')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
                 <div style="width: 100%; padding: 3px; margin-top: 10px; padding-bottom: 1px;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabelTextarea">
                     	     <td style="width: 35%; padding-right: 23px;">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='Echodoppler'>Echodop </span> 
		                            <?php echo $this->formRow($form->get('echodoppler')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
              </td>

              <td style="width:41%; vertical-align: top;">
     
                 <div style="width: 95%; padding: 3px; padding-bottom: 1px; margin-left: 22px; " class="zoneContenuObmrePikaImg">
                    
                    <table style="width: 100%;" >
                      <tr style="width: 100%;" class="designStyleLabel">
                        <td style="width: 20%; padding-right: 23px; vertical-align: top;">
                     	   <label style="width: 100%; height:15px; margin-right: 35px; text-align:left; line-height: 0.7em;">
		                     <span style='font-size: 11px;'>&#10148; </span><span>Scanner</span> 
		                   </label>
                     	</td>
                     		           
                     	<td  rowspan="2" style="width: 80%; padding-right: 23px; vertical-align: top;" id="zonePikaImageSca">
                     	
                     	
                     	
                     	    <!-- PIKACHOOSE -->
	                        <!-- PIKACHOOSE -->
	                        <div id="pikaSca" style=" width: 100%; margin-top: 5px; margin-bottom: -15px;">
	                          <div id="pika2Sca" align="center">
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <div class="pikachoose" style="height: 210px;">
		                           <ul id="pikameSca" class="jcarousel-skin-pika"></ul>
		                        </div>
	                          </div>
	                        </div>
	                        <div id="AjoutImageSca"  class="AjoutImage" style="position: relative; bottom: 25px; left: 15px; float: right;">
	                           <input type='file' name="fichier">
				               <!-- RECUPERER L'IMAGE -->
				               <input type='hidden' id="fichier_tmpSca" name="fichier_tmpSca" />
				               <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
	                        </div>
	                     		  
	                        <script type="text/javascript"> setTimeout(function(){ scriptPikameChooseOther('Sca'); }); </script>      
                     		<script type="text/javascript"> setTimeout(function(){ scriptAddImageInDataBaseOther('Sca'); }); </script>
                     		<script type="text/javascript"> setTimeout(function(){ $("#zonePikaImageSca").hover(function(){ temoinSupprImagePika2 = 53;}); }); </script>
                            <script type="text/javascript"> setTimeout(function(){ getImagesExamensOther('Sca'); });</script>        
                     	
                     	</td>
                     	
                      </tr>
                      
                      <tr style="width: 100%; height: 197px;">
                     	 <td style="width: 20%; padding-right: 23px;" id="imageWaitingSca"></td>
                      </tr>
                      
                      
                    </table>
                   
     
                 </div>
                 
                 <!-- POP UP pour Confirmation Suppression -->
			     <div id="confirmationSca" title="Confirmation de la suppression" style="display:none;">
			       <p style="font-size: 14px;">
			         <span style="float:left; margin:0 0px 20px 0; ">
			           <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
			           Etes-vous s&ucirc;r de vouloir supprimer l'image n&deg;<span id="nbImagesPositionPopupSca"> </span>
			         </span>
			       </p>
			     </div> 
				   
     
              </td>
           </tr>
              
        </table>
        
        
        <table style="width:100%; margin-top: 6px;" >
                         
           <tr style="width: 100%" >
              <td style="width: 59%; vertical-align: top;" class="zoneContenuObmre" >

                 <div style="width: 100%; padding: 3px; padding-bottom: 1px;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabelTextarea">
                     	     <td style="width: 35%; padding-right: 23px;">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='Echographie 1'>Echo 1. </span> 
		                            <?php echo $this->formRow($form->get('echographie1')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
                 <div style="width: 100%; padding: 3px; margin-top: 10px; padding-bottom: 1px;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" class="designStyleLabelTextarea">
                     	     <td style="width: 35%; padding-right: 23px;">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='Echographie 2'>Echo 2. </span> 
		                            <?php echo $this->formRow($form->get('echographie2')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
              </td>

              <td style="width:41%; vertical-align: top;">
     
                 <div style="width: 95%; padding: 3px; padding-bottom: 1px; margin-left: 22px; " class="zoneContenuObmrePikaImg">
                    
                    <table style="width: 100%;" >
                      <tr style="width: 100%;" class="designStyleLabel">
                        <td style="width: 20%; padding-right: 23px; vertical-align: top;">
                     	   <label style="width: 100%; height:15px; text-align:left; line-height: 0.7em;">
		                     <span style='font-size: 11px;'>&#10148; </span><span>Echographie</span> 
		                   </label>
                     	</td>
                     		           
                     	<td  rowspan="2" style="width: 80%; padding-right: 23px; vertical-align: top;" id="zonePikaImageSca">
                     	
                     	
                     	
                     	    <!-- PIKACHOOSE -->
	                        <!-- PIKACHOOSE -->
	                        <div id="pikaEco" style=" width: 100%; margin-top: 5px; margin-bottom: -15px;">
	                          <div id="pika2Eco" align="center">
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <!-- EMPLACEMENT DES IMAGES -->
	                            <div class="pikachoose" style="height: 210px;">
		                           <ul id="pikameEco" class="jcarousel-skin-pika"></ul>
		                        </div>
	                          </div>
	                        </div>
	                        <div id="AjoutImageEco"  class="AjoutImage" style="position: relative; bottom: 25px; left: 15px; float: right;">
	                           <input type='file' name="fichier">
				               <!-- RECUPERER L'IMAGE -->
				               <input type='hidden' id="fichier_tmpEco" name="fichier_tmpEco" />
				               <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
	                        </div>
	                     		  
	                        <script type="text/javascript"> setTimeout(function(){ scriptPikameChooseOther('Eco'); }); </script>      
                     		<script type="text/javascript"> setTimeout(function(){ scriptAddImageInDataBaseOther('Eco'); }); </script>
                     		<script type="text/javascript"> setTimeout(function(){ $("#zonePikaImageEco").hover(function(){ temoinSupprImagePika2 = 54;}); }); </script>
                            <script type="text/javascript"> setTimeout(function(){ getImagesExamensOther('Eco'); });</script>        
                     	
                     	</td>
                     	
                      </tr>
                      
                      <tr style="width: 100%; height: 197px;">
                     	 <td style="width: 20%; padding-right: 23px;" id="imageWaitingEco"></td>
                      </tr>
                      
                      
                    </table>
                   
     
                 </div>
                 
                 <!-- POP UP pour Confirmation Suppression -->
			     <div id="confirmationEco" title="Confirmation de la suppression" style="display:none;">
			       <p style="font-size: 14px;">
			         <span style="float:left; margin:0 0px 20px 0; ">
			           <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
			           Etes-vous s&ucirc;r de vouloir supprimer l'image n&deg;<span id="nbImagesPositionPopupEco"> </span>
			         </span>
			       </p>
			     </div> 
				   
     
              </td>
           </tr>
              
        </table>
        
        
              
     </div>     
              
              
              
     <!-- ******************** Diagnostic à l'entrée ******************-->
     <!-- ******************** Diagnostic à l'entrée ******************-->
     <!-- ******************** Diagnostic à l'entrée ******************-->
    
     <!--*9*-->
     <div style='font-family: police2;font-size: 17px; font-weight: bold;' >Diagnostic &agrave; l'entr&eacute;e</div>
     <div style='max-height: 350px;'>
     
        <table style="width:100%;" >
                         
           <tr style="width: 100%" >
              <td style="width: 59%; vertical-align: top;" class="zoneContenuObmre" >

                 <div style="width: 40%; padding: 3px; padding-bottom: 1px;">
                       
                       <table style="width: 100%;" >
                     	 <tr style="width: 100%" class="designStyleLabel">
                     		        
                     	   <td style="padding-right: 23px;">
                     	     <label style="width: 100%; height:30px; text-align:left;">
		                       <span style='font-size: 11px;'>&#10148; </span><span>Type de Diab&egrave;te</span> 
		                       <?php echo $this->formRow($form->get('type_diabete')); ?> 
		                     </label>
                     	   </td>
                     		        
               		     </tr>
	 			       </table>
	 			       
                 </div>
                 
                 <div style="width: 100%; padding: 3px; margin-top: 6px; padding-bottom: 1px;">
                       <table class="complicationDiagEntre complicationDiagEntree_0"></table>
                 </div>
                 
                 
                 
                 <table style="width:100%;" >
                   <tr style="width: 100%">
                      <td style="width: 20%;">
	 			         <div id='complication_moins' class='examen_physique_pm' onclick='enleverComplicationDiagEntree();' style='display: none;'> &minus; </div> 
	 			         <div id='complication_plus'  class='examen_physique_pm' onclick='ajouterComplicationDiagEntree();' style='display: none;'> + </div>
	 			      </td>
	 			      <td style="width: 80%;" ></td>
	 			   </tr>
	 			 </table>
                 <script type="text/javascript">ajouterComplicationDiagEntree();</script>
                 
              </td>
              
           </tr>
              
        </table>
        
              
     </div>
     
     
     
     <!-- ******************** Traitement ******************-->
     <!-- ******************** Traitement ******************-->
     <!-- ******************** Traitement ******************-->
    
     <!--*9*-->
     <div style='font-family: police2;font-size: 17px; font-weight: bold;' >Traitement</div>
     <div style='max-height: 350px;'>
     
        <table style="width:100%;" >
                         
           <tr style="width: 100%" >
              <td style="width: 59%; vertical-align: top;" class="zoneContenuObmre" >

                 <div style="width: 25%; padding: 3px; padding-bottom: 1px;">
                       
                       <table style="width: 100%;" >
                     	 <tr style="width: 100%" class="designStyleLabel">
                     		        
                     	   <td style="padding-right: 23px;">
                     	     <label style="width: 100%; height:30px; text-align:left;">
		                       <span style='font-size: 11px;'>&#10148; </span><span>Hospitalisation</span> 
		                       <?php echo $this->formRow($form->get('hospitalisation')); ?> 
		                     </label>
                     	   </td>
                     		        
               		     </tr>
	 			       </table>
	 			       
                 </div>
                 
                 

                 <div id="hospitalisationInfos" style="width: 100%; padding: 3px; padding-bottom: 1px; margin-top: 7px; display: none;">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" >
                     	     <td rowspan="2" style="width: 50%; padding-right: 23px;" class="designStyleLabelTextarea">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>Evolution</span> 
		                            <?php echo $this->formRow($form->get('evolution')); ?> 
		                        </label>
                     		 </td>
                     		 <td style="width: 50%; padding-right: 23px;" class="designStyleLabel">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>Exeat</span> 
		                            <?php echo $this->formRow($form->get('exeat')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                     	  
                     	  <tr style="width: 100%" class="designStyleLabel">
                     	     <td style="width: 50%; padding-right: 23px;">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span>D&egrave;c&egrave;s </span> 
		                            <?php echo $this->formRow($form->get('deces')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
                 
                 <div style="width: 100%; padding: 3px; padding-bottom: 1px; margin-top: 8px; ">
                       <table style="width: 100%;" >
                          <tr style="width: 100%" >
                     	     <td style="width: 50%; padding-right: 23px;" class="designStyleLabelTextarea">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='Traitement m&eacute;dical'>Trait. med.</span> 
		                            <?php echo $this->formRow($form->get('evolution')); ?> 
		                        </label>
                     		 </td>
                     		 
                     		 <td style="width: 50%; padding-right: 23px;" class="designStyleLabelTextarea">
                     		    <label style="width: 100%; text-align:left;">
		                          <span style='font-size: 11px;'>&#10148; </span><span title='Traitement chirurgical'>Trait. chir.</span> 
		                            <?php echo $this->formRow($form->get('evolution')); ?> 
		                        </label>
                     		 </td>
                     	  </tr>
                       </table>
                 </div>
                 
                 
                 
                 
                 
              </td>
              
           </tr>
              
        </table>
        
              
     </div>
              
              
              
     
     
</div>


</div>