<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_admission_patient').toggle(true);
$("#menu_admission_patient").replaceWith("<li id='menu_admission_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
dep_menu_admission_patient1();
$('#menu_admission_patient_style').css({'font-weight':'bold','color':'white','font-size':'21px'});

</script>

<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleListePatientsAdmettre.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.css');?>


<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsListePatientsAdmettre.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.js');?>



<?php 
use Consultation\View\Helper\DateHelper;
$Control = new DateHelper();?>
<style>
#contenuInterface{ visibility: hidden; }
</style>

<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenuInterface').fadeIn().css({'visibility':'visible'});
	 
});
</script>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 20px;'><iS style='font-size: 25px;'>&curren;</iS> <span> LISTE DES DOSSIERS PATIENTS </span></div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenuInterface" >
<div id="contenu" >

		<table class="table table-bordered tab_list_mini" id="patientAdmis">
		
		    <thead >
			    <tr >
				    <th id="numero_dossier_" style="width: 14%;"><input type="text" name="search_browser" value=" N&deg; dossier" class="search_init" /></th>
					<th id="nom_" style="width: 14%;"><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="prenom_" style="width: 18%;"><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
					<th id="date_" style="width: 12%;"><input type="text" name="search_browser" value=" Date naissance" class="search_init" /></th>
					<th id="sexe_" style="width: 7%;"><input type="text" name="search_browser" value=" Sexe" class="search_init" /></th>
					<th id="adresse_" style="width: 25%;"><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="effectuer_" style="width: 10%;"><input type="hidden" name="search_browser" value="" class="" /></th>
				</tr>

			</thead>

			<tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px;">

	            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

			</tbody>
		
		</table>
		
		

</div>


<div id="admissionZoneInfos">
   <div id="vue_patient"> </div>
</div>   
   
   

</div>





<!-- POP UP pour Confirmation Suppression -->
<div id="confirmation" title="Confirmation de la suppression" style="display:none;">
  <p style="font-size: 19px;">
     <span style="float:left; margin:0 0px 20px 0; ">
     <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
     Etes-vous s&ucirc;r de vouloir annuler l'admission ?</span>
  </p>
</div>


<div style='display: none;' class='infos_parentales_tampon'> <!-- à ne pas supprimer *** pour les infos parentales --> </div>


<script type="text/javascript">

$(function(){
	initialisation();
});

$('#admissionZoneInfos').toggle(false);

</script>

