<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_consultations').toggle(true);
$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
dep_menu_consultation1();
$('#menu_consultations_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>

<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleListeConsultations.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.css');?>


<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsListeConsultations.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.js');?>



<?php 
use Consultation\View\Helper\DateHelper;
$Control = new DateHelper();?>
<style>
#contenuInterface{ visibility: hidden; }
</style>

<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenuInterface').fadeIn().css({'visibility':'visible'});
	 
});
</script>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 20px;'><iS style='font-size: 25px;'>&curren;</iS> <span> LISTE DES PATIENTS ADMIS </span></div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenuInterface" >
	<div id="contenu" >

		<table class="table table-bordered tab_list_mini" id="patientAdmis">
			<thead>
				<tr style="height:45px; width:100%;">
				    <th id="numero" >N&deg; DOSSIER</th>
					<th id="nom" >NOM</th>
					<th id="prenom" >PRENOM</th>
					<th id="date" >D. NAISSANCE</th>
					<th id="sexe" >SEXE</th>
					<th id="adresse" >ADRESSE</th>
					<th id="effectuer" >OPTIONS</th>
				</tr>
			</thead>

			<tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px; ">

            <!-- ******* On affiche la liste des patients ****** -->

			</tbody>

			<tfoot id="foot" class="foot_style">
				<tr>
					<th id="numero_" style="width: 14%;"><input type="text" name="search_browser" value=" N&deg; dossier" class="search_init" /></th>
					<th id="nom_" style="width: 14%;"><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="prenom_" style="width: 18%;"><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
					<th id="date_" style="width: 12%;"><input type="text" name="search_browser" value=" Date naissance" class="search_init" /></th>
					<th id="sexe_" style="width: 7%;"><input type="text" name="search_browser" value=" Sexe" class="search_init" /></th>
					<th id="adresse_" style="width: 25%;"><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="effectuer_" style="width: 10%;"><input type="hidden" name="search_browser" value="" class="" /></th>
				</tr>
			</tfoot>
		</table>

	</div>

</div>



<script type="text/javascript">
$(function(){
	initialisation();
});
</script>

