<!-- MES STYLES -->
<?php 
echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleCreerDossier.css');
?>

<!-- MES JS -->
<?php
echo $this->headScript ()->appendFile ( $this->basePath () . '/js/consultation/jsCreerDossier.js' );
?>

<script>

var base_url = window.location.toString();
var tabUrl = base_url.split("public");

//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_dossier_patient').toggle(true);
$("#menu_dossier_patient").replaceWith("<li id='menu_dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
dep_menu_dossier_patient1();
$('#menu_liste_dossiers_patients_style').css({'font-weight':'bold','color':'white','font-size':'21px'});


$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
});

</script>

<style>
 #contenu{ visibility: hidden; }
</style>



<?php
$form = $this->form;
$form->setName('formModifierDonneesPatient');
$form->setAttribute ( 'action', $this->url ( 'consultation', array ('action' => 'modifier-dossier') ) );
$form->setAttribute ('enctype','multipart/form-data');
$this->form->prepare ();
echo $this->form ()->openTag ( $form );
?>

<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 30px;'><iS style='font-size: 25px;'>&curren;</iS> MODIFIER L'ETAT CIVIL DU PATIENT</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenu" >
    
    <?php echo $this->formRow($this->form->get('ID_PERSONNE'));?>
    <?php echo $this->formRow($this->form->get('QUARTIER_SAINTLOUIS_MEMO'));?>
    
	<div style='width: 100%;'>
    
	 <div style='width: 15%; height: 150px; float:left;'>
		<div class="photo_patient" id='photo'>
		    <img id="modifier_photo" src="<?php echo $this->basePath().'/images/photos_patients/'.$this->photo.''?>" style=' margin-left:-10px; margin-top:-10px; width:105px; height:105px;'/>
			<input type='file' name="fichier" />
			<!-- RECUPERER L'IMAGE -->
			<input type='hidden' id="fichier_tmp" name="fichier_tmp" />
			<!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
		</div>
     </div>
     
     <div class="supprimer_photo" id="div_supprimer_photo" style="position: absolute; left: 55px; top: 220px;">
			<hass> <input name="supprimer_photo"> </hass>
			<!-- balise sans importance pour le moment -->
	 </div>
     
	 <div style='width: 80%; height: 150px; float:left;'>
		<table id="form_patient" style="float: left;">

			      <tr class="comment-form-patient">
                     <td style="width: 33%;"> <?php echo $this->formRow($this->form->get('NOM'));?></td>
                     <td style="width: 33%;"> <?php echo $this->formRow($this->form->get('TELEPHONE'));?></td>
                     <td style="width: 33%;"> <?php echo $this->formRow($this->form->get('ETHNIE'));?></td>

                  </tr>

                  <tr class="comment-form-patient">
                     <td > <?php echo $this->formRow($this->form->get('PRENOM'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('TELEPHONE_2'));?></td>
                     <td > 
                       <?php echo $this->formRow($this->form->get('RACE'));?>
                       <img onclick="ajouterUneRace();" style="cursor: pointer; position: relative; margin-top: 10px;" src="<?php echo $this->basePath().'/images_icons/light/plus.png'?>" title="Ajouter une race"/> 
                       
                     </td>
                  </tr>

                  <tr class="comment-form-patient">
                     <td style="width: 33%;"> 
                       <div class="age" style="float: left; width: 33%;"> <?php echo $this->formRow($this->form->get('AGE'));?> </div>
                       <div class="date_naiss" style="float: left; width: 60%;"> <?php echo $this->formRow($this->form->get('DATE_NAISSANCE'));?> </div>
                     </td >
                     <td > <?php echo $this->formRow($this->form->get('ORIGINE_GEOGRAPHIQUE'));?> </td>
                     <td > <?php echo $this->formRow($this->form->get('PROFESSION'));?></td>
                  </tr>

                  <tr class="comment-form-patient">
                     <td > <?php echo $this->formRow($this->form->get('SEXE'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('COMMUNE_SAINTLOUIS'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('STATUT_MATRIMONIAL'));?></td>
                  </tr>
                  
                  <tr class="comment-form-patient">
                     <td > <?php echo $this->formRow($this->form->get('ADRESSE'));?> </td>
                     <td >
                       <?php echo $this->formRow($this->form->get('QUARTIER_SAINTLOUIS'));?>
                       <img onclick="ajouterUnQartierDeSaintLouis();" style="cursor: pointer; position: relative; margin-top: 10px;" src="<?php echo $this->basePath().'/images_icons/light/plus.png'?>" title="Ajouter un quartier"/> 
                       
                     </td>
                     <td > <?php echo $this->formRow($this->form->get('REGIME_MATRIMONIAL'));?></td>
                  </tr>


		</table>
	  </div>
		
      
    </div>
    
	<button id="envoyerDonneesForm" style="display:none;"  name="terminer"></button>
	<table style="margin-top: 420px; width: 100%;  height: 12px;">
	  <tr style="">
	  
	  <td style="width: 42%;"></td>
	  <td style="width: 10%;" id="thoughtbot" >
		<button id="annuler"
			style="font-family: police2; font-size: 17px; font-weight: bold;">
			Annuler
		</button>
	  </td>
	  
	  <td style="width: 10%;" id="thoughtbot">
		<button type="submit" id="terminer"
			style=" font-family: police2; font-size: 17px; font-weight: bold;">
			Terminer
		</button>
	  </td>
	  <td style="width: 38%;"></td>
	  
	  </tr>
    </table>

</div>

<!-- POP UP pour Confirmation Suppression -->
<div id="confirmation" title="Confirmation de la suppression"
	style="display: none;">
	<p style="font-size: 16px;">
		<span style="float: left; margin: 0 0px 20px 0;"> <img
			src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />

			Etes-vous s&ucirc;r de vouloir supprimer la photo ?
		</span>
	</p>
</div>



<!-- LES BOUTONS "TERMINER" ou "VALIDER" -->

<?php echo $this->form()->closeTag(); ?>













































<!-- GESTION DE L'INTERFACE D'AJOUT DES TYPES D'ELEMENTS ET ELEMENTS -->
<!-- GESTION DE L'INTERFACE D'AJOUT DES TYPES D'ELEMENTS ET ELEMENTS -->
<!-- GESTION DE L'INTERFACE D'AJOUT DES TYPES D'ELEMENTS ET ELEMENTS -->

<div id="ajouterElements" style="display: none;" >

    <table class="ligneElementsExistantes">
        <tr>
            <td>
               <label id="labListeTypeElement"> Types de elements </label>
               <div class="listeTypeElementsExistantes"> 
                   <table> <!-- Contient la liste des types de elements --> </table>
               </div>
            </td>
            <td>
              <label id="labListeElement">  Elements </label>
              <div class="listeElementsExistantes">
                  <table> <!-- Contient la liste des elements --> </table>
              </div>
            </td>
        </tr>
    </table>
    
    <table class="ligneBoutonsAjout">
        <tr>
            <td>
                <div class="boutonATP"> <button onclick="ajoutTypeElement();"> Ajouter un type de element </button> </div>
            </td>
            <td>
                <div class="boutonAP"> <button onclick="ajoutElement();"> Ajouter un element </button> </div>
            </td>
        </tr>
    </table>
    
    <div id="contenuInterfaceAjoutTypeElements">
    
    <table class="ligneInfosAjoutElements">
        <tr> 
           <td class="LIATP" align="left"><span> <img src='../../../images_icons/chevrons2.png'> Ajout de types d'&eacute;l&eacute;ments </span></td>
           <td class="LIAP"  align="left"><span> <img src='../../../images_icons/chevrons2.png'> </span> <span> Ajout d'&eacute;l&eacute;ments </span></td>
        </tr>
    </table>
    
    <table class="interfaceAjoutElements">
        <tr>
            <td>
               <div class="contenuIAPath">
                  <table>
                     <tr class="champsAjoutTP_0"> </tr>
                     
                     <tr>
                        <td>
                           <img class='iconeAnnulerAP' onclick='enleverUneLigneElement();' src='../../../images_icons/icone_minus.png' >
                           <img class='iconeAjouterAP' onclick='ajouterUneNouvelleLigneElement();' src='../../../images_icons/icone_plus.png' >
                        </td>
                     </tr>
                  </table>
               </div>
            </td>
        </tr>
    </table>
    
    <table class="ligneBoutonsAnnulerValiderAjout">
        <tr>
            <td>
                <div class="boutonAVAA"> <button onclick="annulerAjoutElement();"> Annuler </button> </div>
            </td>
            <td>
                <div class="boutonAVAV"> <button onclick="validerAjoutElement();"> Valider </button> </div>
            </td>
        </tr>
    </table>
    
    </div>
    
</div>




<div id="modifierTypeElement" style="display: none;" >
   <div class="affichageMessageInfos" align="center"> <div> MODIFIER LE TERME SUIVANT </div>  </div>
   <table id="infosConfirmationModification"> </table>
   <div class="affichageMessageInfos" align="center"> <div> PAR </div>  </div>
   <div id="affichageMessageInfosRemplaceModification" align="center"> <input type='text'>  </div>
</div>





<!-- GESTION DE L'INTERFACE D'AJOUT DES ELEMENTS UN VOLET -->
<!-- GESTION DE L'INTERFACE D'AJOUT DES ELEMENTS UN VOLET -->
<!-- GESTION DE L'INTERFACE D'AJOUT DES ELEMENTS UN VOLET -->

<div id="ajouterElementsUV" title="Gestion des informations" style="display: none;" >

    <table class="ligneElementsExistantesUV">
        <tr>
            <td>
              <label id="labListeElementUV">  Elements </label>
              <div class="listeElementsExistantesUV">
                  <table> <!-- Contient la liste des elements --> </table>
              </div>
            </td>
        </tr>
    </table>
    
    <table class="ligneBoutonsAjoutUV">
        <tr>
            <td>
                <div class="boutonAPUV"> <button onclick="ajoutElementUV();">   </button> </div>
            </td>
        </tr>
    </table>
    
    <div id="contenuInterfaceAjoutTypeElementsUV">
    
        <table class="ligneInfosAjoutElementsUV">
            <tr> 
                <td class="LIAPUV"  align="left"> <img src='../../../images_icons/chevrons2.png'> <span> Ajout d'&eacute;l&eacute;ments </span></td>
            </tr>
        </table>
    
        <table class="interfaceAjoutElementsUV">
            <tr>
                <td>
                   <div class="contenuIAPath">
                      <table>
                         <tr class="champsAjoutTPUV_0"> </tr>
                         
                         <tr>
                            <td>
                               <img class='iconeAnnulerAPUV' onclick='enleverUneLigneElementUV();' src='../../../images_icons/icone_minus.png' >
                               <img class='iconeAjouterAPUV' onclick='ajouterUneNouvelleLigneElementUV();' src='../../../images_icons/icone_plus.png' >
                            </td>
                         </tr>
                      </table>
                   </div>
                </td>
            </tr>
        </table>
        
        <table class="ligneBoutonsAnnulerValiderAjout">
            <tr>
                <td>
                    <div class="boutonAVAA"> <button onclick="annulerAjoutElementUV();"> Annuler </button> </div>
                </td>
                <td>
                    <div class="boutonAVAV"> <button onclick="validerAjoutElementUV();"> Valider </button> </div>
                </td>
            </tr>
        </table>
    
    </div>
    
</div>


<div id="modifierTypeElementUV" style="display: none;" >
   <div class="affichageMessageInfosUV" align="center"> <div> MODIFIER LE TERME SUIVANT </div>  </div>
   <table id="infosConfirmationModificationUV"> </table>
   <div class="affichageMessageInfosUV" align="center"> <div> PAR </div>  </div>
   <div id="affichageMessageInfosRemplaceModificationUV" align="center"> <input type='text'>  </div>
</div>













<script> 

    $(document).keypress(function(e){
    	if(e.keyCode == 13){
    		e.preventDefault();
    	}
    });

    $('#DATE_NAISSANCE, #AGE').attr('autocomplete', 'off'); 
    
    $('#annuler').click(function(){ 
		 vart=tabUrl[0]+'public/consultation/liste-dossiers-patients';
	     $(location).attr("href",vart);
	     return false;
	});
    
	//Envoyer le formulaire --- Envoyer le formulaire
	//Envoyer le formulaire --- Envoyer le formulaire
    /*
    $('#terminer').click(function(){

         if($('#SEXE').val() != "" && $('#NOM').val() != "" && $('#PRENOM').val() != "" && $('#AGE').val() != "" ){

            if($('#AGE').val() <= 150 && $('#AGE').val() >= 0){
            	$(this).attr('disabled', true); 
                $('#envoyerDonneesForm').trigger('click');
            }else {
                return true;
            }   
             
         }else{
        	return true;
         }
         
    });
    */


    $('#terminer').click(function(){
   	 
		if($('#formModifierDonneesPatient')[0].checkValidity() == true){
			//formulaire valide et envoi des donnees
			$(this).attr('disabled', true);
    		$('#envoyerDonneesForm').trigger('click');
		}else{
			$('#envoyerDonneesForm').trigger('click');
		}

		
	});
	
    //===============================================
    //===============================================
    //-----------------------------------------------
    //_______________________________________________









	
    $('#TELEPHONE').mask('+221 70 000 00 00');
    $('#TELEPHONE_2').mask('00 000 00 00');


    //Mettre le nom en Majuscule
    //Mettre le nom en Majuscule
    $("#NOM").blur(function(){
 	   $("#NOM").val($("#NOM").val().toUpperCase());
    });

    //Mettre la premiere lettre du prenom en Majuscule
    //Mettre la premiere lettre du prenom en Majuscule
    $("#PRENOM").blur(function(){
 	   var str = $("#PRENOM").val();
 	   var tab = str.split(" ");
 	   var chaine = "";

	   if(str){
	 	   for(var i=0; i<tab.length;i++)
	 	   {
	 		   chaine+=tab[i].substring(0,1).toUpperCase()+tab[i].substring(1,tab[i].length).toLowerCase()+" ";
	 	   }
	   } 

 	   $("#PRENOM").val(chaine);
    });


    setTimeout(function(){ if( $('#DATE_NAISSANCE').val()){ $('#DATE_NAISSANCE').trigger('change'); } });

    $("#COMMUNE_SAINTLOUIS").trigger('change');
    setTimeout(function(){ $("#QUARTIER_SAINTLOUIS").val($("#QUARTIER_SAINTLOUIS_MEMO").val()); },1000);
</script>

