<script>
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_statistiques').toggle(true);
$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.PNG';?>'  /> Statistiques </span></a></li>");
dep_menu_statistiques1();
$('#menu_statistiques_style').css({'font-weight':'bold','color':'white','font-size':'21px'});
</script>

<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleListeConsultations.css');?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jqueryCharts/jquery.canvasjs.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/facturation/informationsStatistiques.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/zingchart/zingchart.min.js');?>
    		
<!-- JS & CSS de anychart -->  
<!-- JS & CSS de anychart -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-base.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-ui.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-cartesian-3d.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-exports.min.js');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/anychart/css/anychart-ui.min.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/anychart/fonts/css/anychart-font.min.css');?>




<style>
#contenuInterface{ visibility: hidden; }
</style>

<script>
$(window).load(function () {
	setTimeout(function(){
		$('#wait').toggle(false);
		$('#contenuInterface').fadeIn().css({'visibility':'visible'}); 
	});
});
</script>


 <style type="text/css">
  	
  	#t {
  width: 100%;
  background-color: #f1f1c1;
  margin-bottom: 2px;
  padding: 2px;
}
#t tr:nth-child(even) {
  background-color: #eee;
}
#t tr:nth-child(odd) {
  background-color: #fff;
}
#t th {
  color: white;
  background-color: black;
}
	
	table, th, td {
		border: 0px solid black;
        border-collapse: collapse;
}
	th, td {
  padding: 15px;
  margin-bottom: 2px;
  
}

#a {
  border: 1px dashed #ccc;
    border-top-right-radius: 40px;
	border-top-left-radius: 40px;
	border-bottom-right-radius: 40px;
	border-bottom-left-radius: 40px;
	color: blue;
	margin: 14px;
	font-size: 25px;
	text-align: center;
	text-shadow: green;
	text-transform: capitalize;
	vertical-align: middle;
	padding: 10px;
	padding-top: 40px;
	border: 6px solid #ccc;
	box-shadow: 0pt 7pt 10px rgba(0, 0, 0, 1.5);
}


  </style>
  
<script type="text/javascript">
	var donnees = new Array();
</script>

 <?php 
 
 $resultTab1 = $this->result1[0];
 $resultTab2 = $this->result1[1];
 for ($i=0 ; $i<count($resultTab1); $i++) {
 ?>

<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

  //alert("<?php echo $resultTab1[$i]; ?>");

   var variable = { y: <?php echo $resultTab2[$resultTab1[$i]]; ?> , label:"<?php echo $resultTab1[$i]; ?>"};
   donnees.push(variable);
</script>
 
<?php } ?>
 
 <script>
window.onload = function () {
	CanvasJS.addColorSet("greenShades",
                [//colorSet Array

                "#2F4F4F",
                "#008080",
                "#2E8B57"
                //"#3CB371",
                //"#90EE90"                
                ]);

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	theme: "light1", // "light1", "light2", "dark1", "dark2"
	title:{
		text: "Visualisation du Patients Diabetes"
	},
	 colorSet: "greenShades",
	axisY: {
		title: "Nombre de Patients"
	},

	data: [{        
		type: "pie",  //change type to bar, line, area, pie, etc 
		showInLegend: true, 
		//legendMarkerColor: "blue",
		indexLabel:"{y}",
		//indexLabel:"{label}",
		legendText: "{label}",
		dataPoints: donnees
			
	}]
});


var chart8 = new CanvasJS.Chart("chartContainer8", {
	animationEnabled: true,
	theme: "dark1", // "light1", "light2", "dark1", "dark2"
	title:{
		text: "Visualisation du Patients Diabetes"
	},
	axisY: {
		title: "Nombre de Patients"
	},
	data: [{        
		type: "bar",  
		showInLegend: true, 
		indexLabel:"{y}",
		legendMarkerColor: "green",
		//indexLabel:"{y}",
		legendText: "Nombre de Patients par Categorie Age",
		dataPoints: donnees8
			
}]
});
var chart1 = new CanvasJS.Chart("chartContainer1", {
	animationEnabled: true,
	theme: "light1", // "light1", "light2", "dark1", "dark2"
	title:{
		text: "Visualisation du Patients Diabetes"
	},
	axisY: {
		title: "Nombre de Patients"
	},
	data: [{        
		type: "column",  
		showInLegend: true, 
		legendMarkerColor: "grey",
		indexLabel:"{y}",
		legendText: "Nombre de Patients par Commune",
		dataPoints: donnees1
			
	}]
});

var chart5 = new CanvasJS.Chart("chartContainer5", {
	animationEnabled: true,
	theme: "light1", // "light1", "light2", "dark1", "dark2"
	title:{
		text: "Visualisation du Patients Diabetes"
	},
	colorSet: "greenShades",
	axisY: {
		title: "Nombre de Patients"
	},
	data: [{        
		type: "column",  
		showInLegend: true, 
		legendMarkerColor: "blue",
		indexLabel:"{y}",
		legendText: "Nombre de Patients par Types Diabetes",
		dataPoints: donnees5
			
	}]
});






chart.render();
chart8.render();
chart1.render();
chart5.render();

}
</script>

<script type="text/javascript">
	var donnees1 = new Array();
</script>

 

<?php 
 
 $resultTab3 = $this->result2[0];
 $resultTab4 = $this->result2[1];
 for ($i=0 ; $i<count($resultTab3); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab4[$resultTab3[$i]]; ?> , label:"<?php echo $resultTab3[$i]; ?>"};
   donnees1.push(variable);
</script>
 
<?php } ?>
 
 



<script type="text/javascript">
	var donnees5 = new Array();
</script>

 

<?php 
 
 $resultTab11 = $this->result6[0];
 $resultTab12 = $this->result6[1];
 for ($i=0 ; $i<count($resultTab11); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab12[$resultTab11[$i]]; ?> , label:"<?php echo $resultTab11[$i]; ?>"};
   donnees5.push(variable);
</script>
 
<?php } ?>
 
 


<script type="text/javascript">
	var donnees8 = new Array();
</script>

 

<?php 
 
 $resultTab17 = $this->result9[0];
 $resultTab18 = $this->result9[1];
 for ($i=0 ; $i<count($resultTab17); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab18[$resultTab17[$i]]; ?> , label:"<?php echo $resultTab17[$i]; ?>"};
   donnees8.push(variable);
</script>
 
<?php } ?>
 
 

<div id="a" style="width: 90%;" align="center">
	
	<table  class="table" style=" width:100%; height: 400px;  border: 0px solid #cccccc;">
	<caption><h3>dashboard</h3></caption>
	<tr>
		<td id="chartContainer" ></td>
		<td id="chartContainer1"></td>

	</tr>


	<tr>
		<td id="chartContainer8" ></td>
		<td id="chartContainer5" ></td>

	</tr>
   </table>

  
</div>


