<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/admin/styleAuthentification.css');?> 

<div class="login-form">
   <div class="head">	
      <img src="<?php echo $this->basePath().'/images/logoAuth7.jpg'; ?>" >					
   </div>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute ( 'action', $this->url ( 'admin', array ('action' => 'login') ));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);
?>
<!-----start-main---->
<div id="message_error" style="padding-bottom: 10px; text-align: center; font-family: Times New Roman; color: red;"><i>nom d'utilisateur ou mot de passe incorrect</i></div>

<ul>
	<li>
	  <?php echo $this->formRow($form->get('username')); ?>
	  <a  class=" icon user"></a>
	</li>
	<li>
	   <?php echo $this->formRow($form->get('password')); ?>
	   <a class=" icon lock"></a>
	</li>
</ul>
				
<div class="p-container">
	 <label class="checkbox" ><i></i>Mot de passe oubli&eacute; ?</label>
	 <?php echo $this->formSubmit($form->get('submit'));?>
</div>


<?php echo $this->form()->closeTag();?>

</div>
<!--//End-login-form-->

<!-----start-copyright---->
<div class="copy-right">
	<p style="color: #45ed0a;">SIMENS<khasss style="color: red; font-size: 20px;">+ </khasss>  <a target="_blank" href="http://www.simens.sn" style="color:white; font-size: 14px;">site-web</a></p> 
</div>
<!-----//end-copyright---->


<script> 
$('#username').attr('autocomplete', 'off'); 
</script>

<?php if($this->erreur_message == 1) {?>
         <script> 
             $('#message_error').toggle(true);
         </script>
<?php } else {?>
         <script> 
             $('#message_error').toggle(false);
         </script>
<?php }?>