<?php

 echo $this->headLink()->prependStylesheet($this->basePath().'/css/bootstrap.min.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-style-cons.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-media.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/smoothness/jquery-ui.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/js/w2ui/w2ui-1.4.3.min.css');
  
 $this->headScript()->appendFile($this->basePath().'/js/jquery.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/jquery.mask.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/bootstrap.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/jquery-ui.js');
 $this->headScript()->appendFile($this->basePath().'/js/w2ui/w2ui-1.4.3.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/html2canvas.min.js');

  echo $this->headScript()->appendFile($this->basePath().'/js/plugins/zingchart/zingchart.min.js');
  echo $this->headScript()->appendFile($this->basePath().'/js/jquery.min.js');
  echo $this->headScript()->appendFile($this->basePath().'/js/jquery.mask.min.js');
  echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jqueryCharts/canvasjs.min.js');

?>
<!-- JS & CSS de anychart -->  
<!-- JS & CSS de anychart -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-base.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-ui.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-cartesian-3d.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jsPDF-master/jspdf.min.js');
  ?>

<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-exports.min.js');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/anychart/css/anychart-ui.min.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/anychart/fonts/css/anychart-font.min.css');?>
<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleListeConsultations.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.css');?>


<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsListeConsultations.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.js');?>

<style type="text/css">

#table{

}
.st{
	align-self: center;
	width: 40%; 
	height: 300px;
	border: 1px dashed #ccc;
    border-top-right-radius: 5px;
	border-top-left-radius: 5px;
	border-bottom-right-radius: 5px;
	border-bottom-left-radius: 5px;
	color: blue;
	margin: 8px;
	font-size: 15px;
	text-align: center;
	text-shadow: green;
	text-transform: capitalize;
	vertical-align: middle;
	padding: 5px;
	padding-top: 15px;
	border: 3px solid #ccc;
	
}

</style>

<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 20px;'><iS style='font-size: 25px;'>&curren;</iS> <span> STATISTIQUES DES PATIENTS  </span></div>

<div id="contenuInterface" >
	<div id="contenu" >
<table style="width: 100%">
<!--	<caption><h3>STATISTIQUES </h3></caption>-->
	<tr style="width: 100%; height: 500px;" >    
		<td style="width: 30%; height: 500px; background-color: ;"> 
		
	<button id="nbsex" type="button" class="btn btn-outline-success btn-block " style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;">Nombre Patient Par Sexe </button>
	<button id="nbcat" type="button" class="btn btn-outline-success btn-block" style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;">Nombre Patient Par CategorieAge</button>
	<button id="nbcom" type="button" class="btn btn-outline-success btn-block" style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;">Nombre Patient Par Commune </button>
	<button id="nbqua" type="button" class="btn btn-outline-success btn-block" style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;">Nombre Patient Par Quartier</button>
	<button id="nbsta" type="button" class="btn btn-outline-success btn-block" style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;">  Nombre Patient Par Statue Matrimoniale</button>
	<button id="nbcomp" type="button" class="btn btn-outline-success btn-block" style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;">Nombre Patient Par Complication </button>
	<button id="nbprof" type="button" class="btn btn-outline-success btn-block" style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;"> Nombre Patient Par Profession</button>
	<button id="nbtyp" type="button" class="btn btn-outline-success btn-block" style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;">Nombre Patient Par  Types Diabetes </button>

	<button id="nbevo" type="button" class="btn btn-outline-success btn-block" style="align-self: center;width: 50%; height: 40px;border: 1px dashed #ccc;font-size: 15px;text-align: center; border: 1px solid #ccc;">Evolution Patient Par Date Cons </button>


 </td>

		<td id="AffichageGraphe" style="width: 70%; height: 300px; background-color: gree;"> </td>
		<!-- <td id="patientsSexe" style="width: 70%; height: 200px; background-color: gree;">  </td>-->
		
	</tr>	
	

</table>


<!--
<table id="table" style="width: 50%;">
	<tr>
		<td style='width: 25% height: 100px; '>
			<a href="#">
				<span onclick="popupPatientParSexe()" class="module" id ="popup"style="color:green; font-size: 13px;"> Nombre Patient Par Sexe </span>
			</a>
		
		</td>

		<td style='width: 25%; height: 100px; '>
			<a href="#">
			<span onclick="popupPatientParAge()" class="module" style="color:green; font-size: 13px;"> Nombre Patient Par CategorieAge </span>
			</a>
		</td>

		<td style='width: 25%; height: 100px; '>
			<a href="#">
				<span onclick="popupPatientParCommune()" class="module" style="color:green; font-size: 13px;"> Nombre Patient Par Commune  </span>
			</a> 
			
		</td>

		<td style='width: 25%; height: 100px; '>
			<a href="#">
				<span onclick="popupPatientParQuatier()"  class="module" style="color:green;font-size: 13px;"> Nombre Patient Par Quartier </span>

			</a>
			
		</td>
	</tr>

	<tr>
		<td style='width: 25%; height: 100px; '>
			<a href="#">
				<span onclick="popupPatientParStatM()" class="module" style="color:green; font-size: 13px;"> Nombre Patient Par Statue Matrimoniale </span>
			</a>
			
		</td>

		<td style='width: 25%; height: 100px; '>
			<a href="#">
				<span onclick="popupPatientParCompli()" class="module" style="color:green; font-size: 13px;">Nombre Patient Par Complication</span>
			</a>
			
		</td>

		<td style='width: 25%; height: 100px; '>
		 <a href="#">
		 	<span onclick="popupPatientParProf()" class="module" style="color:green; font-size: 13px;">Nombre Patient Par Profession</span>
		 </a>	 
		</td>

		<td style='width: 25%; height: 100px; '>
			<a href="#">
				<span onclick="popupPatientParTypeD()" class="module" style="color:green; font-size: 13px;">Nombre Patient Par  Types Diabetes</span>
			</a>
			
		</td>
	</tr>
</table>
</div>
       -->


	<!--  Patient Par Sexe -->

<div id="idPopupPatientParSexe" title="Patient Par Sexe" style="display:none;">
	<div style='width: 100%; height: 10px; position:left;'> 
		<!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
     <!-- <a href="#" onclick="pdfGen()">PDF</a> -->
    </div>
   <!-- <button onclick="download()">pdf</button> -->
   <div id="pSex" style="width: 100%;" align="center">
   	
   	<table id="table1" style="width: 70%; height: 100px; border: 1px solid #cccccc;">
   		<caption>Repartition de patients par sexe</caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc;">
 		<?php for( $i = 0 ; $i < count($this->result1[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result1[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result1[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result1[1][$this->result1[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientSexe[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>
   </div>
   
   <div id="gsex" style="width: 100%;" align="center">
   	
   	<table id="table2" style="width: 90%; height: 190px; border: 1px solid #cccccc; background-color: gren;">
   		<caption>Visualisation de patients par sexe</caption>
  		<tr style="width: 90%; height: 50px; border: 1px solid #cccccc; vertical-align: bottom;">
 		<td id="patientsSexe"> 
      
    	<script type="text/javascript">

    	


			var donnees = new Array();
		</script>

 <?php 
 
  
 $resultTab1 = $this->result1[0];
 $resultTab2 = $this->result1[1];
 for ($i=0 ; $i<count($resultTab1); $i++) {
 ?>

<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);
   

 //alert("<?php echo $resultTab1[$i]; ?>");

   var variable = { y: <?php echo $resultTab2[$resultTab1[$i]]; ?> , x:"<?php echo $resultTab1[$i]; ?>"};
   donnees.push(variable);
//var nbPatientSM   = <?php //echo $this->resultSM; ?> // 
//var nbPatientSF   = <?php //echo $this->resultSF; ?> 
</script>
 
<?php } ?>
 
 <script>//alert(donnees);
$(document).ready(function($) {
var chartPatientSexe;
function patientsSexeAnyChart() {
		anychart.onDocumentReady(function () {
		    // create column chart 
		    chartPatientSexe = anychart.column3d();
		    // turn on chart animation
		    chartPatientSexe.animation(true);

		    // set chart title text settings
		    chartPatientSexe.title('');
		    // create area series with passed data
		    chartPatientSexe.column(donnees);

		    chartPatientSexe.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');
		    // set scale minimum
		    chartPatientSexe.yScale().minimum(0);
		    // set yAxis labels formatter
		    chartPatientSexe.yAxis().labels().format('{%Value}{groupsSeparator: }');
		    chartPatientSexe.tooltip().positionMode('point');
		    chartPatientSexe.interactivity().hoverMode('by-x');
		    chartPatientSexe.xAxis().title('');
		    chartPatientSexe.yAxis().title('');
		    chartPatientSexe.labels('y');

	    // set container id for the chart
		    chartPatientSexe.container('patientsSexe');
		   // initiate chart drawing
		    chartPatientSexe.draw();
			});
	}

	patientsSexeAnyChart();
});

</script>

</td>
</tr>
</table>
   </div>
  	
			
</div>

<script type="text/javascript">

 $(document).ready(function(){

	$("#nbsex").mouseover(function(){
		$("#AffichageGraphe").html($("#idPopupPatientParSexe").html()).css("visibility", "visible");
		
	});	
	});
/*
 $(document).ready(function(){

	$("#nbsex").onclick(function(){
		$("#AffichageGraphe").html($("#idPopupPatientParSexe").html());
		
	});	
	});
*/

</script>






<!--  Patient Par CategorieAge -->
<div id="idPopupPatientParAge" title="Patient Par CategorieAge" style="display:none; overflow-x:auto;">
	<div style='width: 100%; height: 10px; position:left;'>    
      <!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
    </div>

    <div style="width: 100%;" align="center" >
    	
    <table id="table3" style="width: 70%; height: 100px; border: 1px solid #cccccc;">
  	<caption>Repartition  de patients par CategorieAge</caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc;">
 		<?php for( $i = 0 ; $i < count($this->result9[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result9[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result9[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result9[1][$this->result9[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientCatAge[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>
    </div>
  
  	<div style="width: 100%;" align="center">
  		
  	<table id="table4" style="width: 90%; height: 190px; border: 1px solid #cccccc; background-color: gren;">

  	 <caption> Visualisation de patients par CategorieAge</caption>
 	<tr style="width: 90%; height: 50px; border: 1px solid #cccccc; vertical-align: bottom;" >
 		<td id="PatientsCatAge"> 

      <script type="text/javascript">
	var donnees8 = new Array();
</script>

 

<?php 
 
 $resultTab17 = $this->result9[0];
 $resultTab18 = $this->result9[1];
 for ($i=0 ; $i<count($resultTab17); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab18[$resultTab17[$i]]; ?> , x:"<?php echo $resultTab17[$i]; ?>"};
   donnees8.push(variable);



</script>
 
<?php } ?>
 

 
 <script>//alert(donnees);
$(document).ready(function($) {

  // anychart.theme('darkBlue');
  function PatientsCatAgeBarAnyChart() {

    	anychart.onDocumentReady(function () {
    	    // create bar chart
    	    var chart = anychart.bar3d();

    	    // turn on chart animation
    	    chart.animation(true);

    	    // set chart padding
    	    chart.padding([10, 40, 5, 20]);

    	    // set chart title text settings
    	    chart.title('');

    	    // create area series with passed data
    	    chart.bar( donnees8 );

    	    // set tooltip settings
    	    chart.tooltip()
    	            .positionMode('point')
    	            .format('{%Value}')
    	            .position('right')
    	            .anchor('left-center')
    	            .offsetX(5)
    	            .offsetY(0);

    	    // set yAxis labels formatter (axeY)
    	    chart.yAxis().labels().format('{%Value}');

    	    // set titles for axises
    	    chart.xAxis().title('');
    	    chart.yAxis().title('Nombre de Patients Par CategorieAge');
    	    chart.interactivity().hoverMode('by-x');
    	    chart.labels('y');
    	    // set scale minimum
    	    chart.yScale().minimum(0);

    	    // set container id for the chart
    	    chart.container('PatientsCatAge');

    	    // initiate chart drawing
    	    chart.draw();
    	});

	}
PatientsCatAgeBarAnyChart();

});
</script>
</td>
</tr>
</table>


  	</div>
  	    
</div>

<script type="text/javascript">

$(document).ready(function(){

	$("#nbcat").click(function(){
		$("#AffichageGraphe").html($("#idPopupPatientParAge").html());
		
	});	
	});



</script>




<!-- POP UP Patient Par Commune -->
<div id="idPopupPatientParCommune" title="Patient Par Commune" style="display:none;">
	<div style='width: 100%; height: 10px; position:left;'>    
      <!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
    </div>

	<div style="width: 100%;" align="center">
		<table id="table5" style="width: 70%; height: 100px; border: 1px solid #cccccc;">
  	<caption> Repartition de patients Par Commune </caption>
 	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc;">
 		 <?php for( $i = 0 ; $i < count($this->result2[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result2[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result2[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result2[1][$this->result2[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientCom[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>
 
	</div>

	<div style="width: 100%;" align="center">
		
		<table id="table6"  style="width: 90%; height: 300px; border: 1px solid #cccccc; background-color: gren;">
  	<caption> Visualisation de patients Par Commune </caption>
 	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc; vertical-align: bottom;">
 		<td id="patientsCom"  style="width: 100%; border: 1px solid #cccccc;"> 
 
      

<script type="text/javascript">
	var donnees1 = new Array();
</script>

 

<?php 
 
 $resultTab3 = $this->result2[0];
 $resultTab4 = $this->result2[1];
 for ($i=0 ; $i<count($resultTab3); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = {y: <?php echo $resultTab4[$resultTab3[$i]]; ?>,x:"<?php echo $resultTab3[$i]; ?>" };
   donnees1.push(variable);

</script>
 
<?php } ?>

 
 <script>//alert(donnees);
$(document).ready(function($) {
function patientsComAnyChart() {

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		   
		    chart.column(donnees1
    	           	    );


		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('Nombre de Patients Par Commune');
		    chart.labels('label');
		    chart.labels('y');

		    // set container id for the chart
		    chart.container('patientsCom');

		    // initiate chart drawing
		    chart.draw();
		});

	}

  patientsComAnyChart();
});
</script>
</td>
</tr>
</table>
</div>
  	
    
</div>

<script type="text/javascript">


	$(document).ready(function(){

	$("#nbcom").click(function(){
		$("#AffichageGraphe").html($("#idPopupPatientParCommune").html());
		
	});	
	});

</script>





<!--  Patient Par Quartier -->
<div id="idPopupPatientParQuartier" title="Patient Par Quartier" style="display:none;">
	<div style='width: 100%; height: 10px; position:left;'>    
<!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
    </div>

	<div style="width: 800px; overflow:scroll; "align="center" >
	<table id="table7" style="width: 43%; height: 100px; border: 1px solid #cccccc;">
    <caption> Repartition de patients Par Quartier</caption>
 	<tr style="width: 90%; height: 50px; border: 1px solid #cccccc;">
 		<?php for( $i = 0 ; $i < count($this->result3[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result3[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 50%; height: 30px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result3[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result3[1][$this->result3[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientQua[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>
	</div>
    
  	  <div  style="width: 93%;" align="center" >
  	<table id="table8" style="width: 95%; height: 400px; border: 1px solid #cccccc; background-color: gren;">
  	<caption> Visualisation de patients Par Quartier</caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc; vertical-align: bottom;">
 		<td id="patientsQua" style="width: 100%; border: 1px solid #cccccc;" > 
 
      
<script type="text/javascript">
	var donnees2 = new Array();
</script>

 <?php 
 
 $resultTab5 = $this->result3[0];
 $resultTab6 = $this->result3[1];
 for ($i=0 ; $i<count($resultTab5); $i++) {
 ?>
<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab6[$resultTab5[$i]]; ?> , x: "<?php echo $resultTab5[$i]; ?>"};
   donnees2.push(variable);
</script>
 
<?php } ?>

 
 <script>//alert(donnees);
$(document).ready(function($) {
function patientsQuaAnyChart(){

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.column(donnees2
    	           	    );

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('Nombre de Patients Par Quartier');
		    chart.labels('label');
		    chart.xAxis().labels().rotation(-70);
		    chart.labels('y');

		    // set container id for the chart
		    chart.container('patientsQua');

		    // initiate chart drawing
		    chart.draw();
		});

	}

  patientsQuaAnyChart();
});
</script>
</td>
</tr>
</table>
  	</div>
    
</div>

<script type="text/javascript">
$(document).ready(function(){

	$("#nbqua").click(function(){
		$("#AffichageGraphe").html($("#idPopupPatientParQuartier").html());
		
	});	
	});

</script>



<!--  Patient Par StatueMatrimonial-->
<div id="idPopupPatientParStatM" title="Patient Par StatueMatrimonial" style="display:none;">
	<div style='width: 100%; height: 10px; position:left;'>    
      <!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
    </div>

	<div style="width: 100%;" align="center">
		<table id="table9" style="width: 70%; height: 100px; border: 1px solid #cccccc;">
 	<caption> Repartition de Patients Par StatueMatrimonial </caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc;">
 		<?php for( $i = 0 ; $i < count($this->result4[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result4[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result4[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result4[1][$this->result4[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientSm[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>		
	</div>
 	

<div style="width: 100%;" align="center">
	
  	<table id="table10" style="width: 90%; height: 300px; border: 1px solid #cccccc; background-color: gren;">
  	<caption> Visualisation  de Patients Par StatueMatrimonial </caption>
  	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc; vertical-align: bottom;">
 		<td id="patientsStat"> <script type="text/javascript">
	var donnees3 = new Array();
</script>

 

<?php 
 
 $resultTab7 = $this->result4[0];
 $resultTab8 = $this->result4[1];
 for ($i=0 ; $i<count($resultTab7); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab8[$resultTab7[$i]]; ?> , x:"<?php echo $resultTab7[$i]; ?>"};
   donnees3.push(variable);
</script>
 
<?php } ?>
 <script>//alert(donnees);
$(document).ready(function($) {
function patientsStatMAnyChart(){

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.column(donnees3
    	           	    );

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('Nombre de Patients Par StatueMatrimonial');
		    chart.labels('label');
		    chart.labels('y');

		    // set container id for the chart
		    chart.container('patientsStat');

		    // initiate chart drawing
		    chart.draw();
		});

	}

  patientsStatMAnyChart();
});
</script>
  </td>
  </tr>
 </table>
 

</div>
    
</div>

<script type="text/javascript">

    $(document).ready(function(){

	$("#nbsta").click(function(){
		$("#AffichageGraphe").html($("#idPopupPatientParStatM").html());
		
	});	
	});
</script>



<!-- POP UP Patient Par Complication-->
<div id="idPopupPatientParCompli" title="Patient Par Complication" style="display:none;">
	<div style='width: 100%; height: 10px; position:left;'>    
      <!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
    </div>

	<div style="width: 100%;" align="center">
		
		<table id="table11" style="width: 70%; height: 100px; border: 1px solid #cccccc;">
 	<caption> Repartition de Patients Par Complication </caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc;">
 		<?php for( $i = 0 ; $i < count($this->result7[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result7[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result7[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result7[1][$this->result7[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientComp[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>


	</div>
 <div style="width: 100%;" align="center">
	
 
  	<table id="table12" style="width: 90%; height: 300px; border: 1px solid #cccccc; background-color: gren;">
  		<caption> Visualisation de Patients Par Complication </caption>
  	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc; vertical-align: bottom;">
 		<td id="patientsCompli"> 
 
<script type="text/javascript">
	var donnees6 = new Array();
</script>

 

<?php 
 
 $resultTab13 = $this->result7[0];
 $resultTab14 = $this->result7[1];
 for ($i=0 ; $i<count($resultTab13); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab14[$resultTab13[$i]]; ?> , x:"<?php echo $resultTab13[$i]; ?>"};
   donnees6.push(variable);
</script>
 
<?php } ?>
 

 
<script>//alert(donnees);
$(document).ready(function($) {
function patientsCompliAnyChart(){

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.column(donnees6
    	           	    );

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('Nombre de Patients Par  Complication');
		    chart.labels('label');
		    chart.labels('y');

		    // set container id for the chart
		    chart.container('patientsCompli');

		    // initiate chart drawing
		    chart.draw();
		});

	}

  patientsCompliAnyChart();
});
</script>
</td>
</tr>
</table>

</div>

    


<script type="text/javascript">

	$(document).ready(function(){

	$("#nbcomp").click(function(){
		$("#AffichageGraphe").html($("#idPopupPatientParCompli").html());
		
	});	
	});

	
	
</script>



 




<!--  Patient Par Types Diabete-->
<div id="idPopupPatientParTypeD" title="Patient Par Types Diabetes" style="display:none;">
	<div style='width: 100%; height: 10px; position:left;'>    
     <!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
    </div>

  
  <div style="width: 100%;" align="center">
 	
 	<table id="table13" style="width: 70%; height: 100px; border: 1px solid #cccccc;">
 	<caption> Repartition  de Patients Par Types Diabete </caption>
 	<tr style="width: 90%; height: 50px; border: 1px solid #cccccc;">
 		<?php for( $i = 0 ; $i < count($this->result6[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result6[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 90%; height: 50px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result6[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result6[1][$this->result6[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientTd[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>
 	
  </div>
 
  	<div style="width: 100%;" align="center">
  		
  		<table id="table14" style="width: 90%; height: 100px; border: 1px solid #cccccc; background-color: gren;">
  		<caption> Visualisation de Patients Par Types Diabete </caption>
 	<tr style="width: 90%; height: 50px; border: 1px solid #cccccc; vertical-align: bottom;">
 		<td id="patientsTypes"> 
 
 	

<script type="text/javascript">
	var donnees5 = new Array();
</script>

 

<?php 
 
 $resultTab11 = $this->result6[0];
 $resultTab12 = $this->result6[1];
 for ($i=0 ; $i<count($resultTab11); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab12[$resultTab11[$i]]; ?> , x:"<?php echo $resultTab11[$i]; ?>"};
   donnees5.push(variable);
</script>
 
<?php } ?>

	
 
<script>//alert(donnees);
$(document).ready(function($) {
function patientsTypeDAnyChart(){

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.column(donnees5
    	           	    );

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('Nombre de Patients Par Types Diabetes');
		    //chart.labels('label');
		    chart.labels('y');
		    // set container id for the chart
		    chart.container('patientsTypes');

		    // initiate chart drawing
		    chart.draw();
		});

	}

  patientsTypeDAnyChart();
});
</script>
</td>
</tr>
</table>		
	
  	</div>	
    
</div>

<script type="text/javascript">


	$(document).ready(function(){

	$("#nbtyp").click(function(){
		$("#AffichageGraphe").html($("#idPopupPatientParTypeD").html());
		
	});	
	});

</script>



<!--  Patient Par Profession-->
<div id="idPatientParProf" title="Patient Par Profession" style="display:none;">
	<div style='width: 100%; height: 10px; position:left;'>    
      <!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
    </div>

	<div style="width: 100%;" align="center">
		<table id="table15" style="width: 70%; height: 100px; border: 1px solid #cccccc;">
    	<caption> Repartition de Patients Par Profession </caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc;">
 		<?php for( $i = 0 ; $i < count($this->result5[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result5[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result5[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result5[1][$this->result5[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientPr[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>
	
	</div>
    
    <div style="width: 100%;" align="center">
    	
    	<table id="table16" style="width: 90%; height: 300px; border: 1px solid #cccccc; background-color: gren;">
  		<caption> Visualisation de Patients Par Profession </caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc; vertical-align: bottom;">
 		<td id="patientsProf"> 
 
 
	

<script type="text/javascript">
	var donnees4 = new Array();
</script>

 

<?php 
 
 $resultTab9 = $this->result5[0];
 $resultTab10 = $this->result5[1];
 for ($i=0 ; $i<count($resultTab9); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTab10[$resultTab9[$i]]; ?> , x:"<?php echo $resultTab9[$i]; ?>"};
   donnees4.push(variable);
</script>
 
<?php } ?>

 
<script>//alert(donnees);
$(document).ready(function($) {
function patientsProfAnyChart(){

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.column(donnees4
    	           	    );

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('Nombre de Patients Par  Profession');
		    chart.labels('label');
		    //chart.xAxis().labels().rotation(-50);
		    chart.labels('y');
		    // set container id for the chart
		    chart.container('patientsProf');

		    // initiate chart drawing
		    chart.draw();
		});

	}

  patientsProfAnyChart();
});
</script>
</td>
</tr>
</table>
	
    </div>
  	
    
</div>

<script type="text/javascript">

	 $(document).ready(function(){

	$("#nbprof").click(function(){
		$("#AffichageGraphe").html($("#idPatientParProf").html());
		
	});	
	});
</script>

	

</div>



<!-- Evolution Patient Par Date-->
<div id="idPatientParDate" title="Patient Par Date" style="display:none;">
	<div style='width: 100%; height: 10px; position:left;'>    
 <!--     <img onclick="" style=" cursor: pointer;" src='../images_icons/pdf.png' />-->
    </div>

	<div style="width: 100%; overflow:scroll; "align="center">
		<table id="table15" style="width: 70%; height: 100px; border: 1px solid #cccccc;">
    	<caption> Repartition de Patients Par Date du Consultation  </caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc;">
 		<?php for( $i = 0 ; $i < count($this->result10[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		
  		<?php echo $this->result10[0][$i]; ?>
  	</td>
  	<?php } ?>
  	</tr>
  	<tr style="width: 100%; height: 30px; border: 1px solid #cccccc;">

  		<?php for( $i = 0 ; $i < count($this->result10[0]) ; $i++){  ?>
  	<td style="min-width: 80px; border: 2px solid #cccccc;">
  		<span style="font-weight: bold;"><?php echo $this->result10[1][$this->result10[0][$i]]; ?> </span>
  		<?php echo ' - ('.$this->pourcentagePatientEvo[$i].'%)'; ?>
  		<?php // echo $this->result2[0][$i]; ?>
  	</td>
  <?php } ?> 
  	</tr>
  	</table>
	
	</div>
    
    <div style="width: 100%;" align="center">
    	
    	<table id="table16" style="width: 90%; height: 300px; border: 1px solid #cccccc; background-color: gren;">
  		<caption> Visualisation de Patients  Date du Consultation </caption>
 	<tr style="width: 100%; height: 50px; border: 1px solid #cccccc; vertical-align: bottom;">
 		<td id="patientsDate"> 
 
 
	

<script type="text/javascript">
	var donneese1 = new Array();
</script>

 

<?php 
 
 $resultTabe1 = $this->result10[0];
 $resultTabe2 = $this->result10[1];
 for ($i=0 ; $i<count($resultTabe1); $i++) {
 ?>


<script type="text/javascript"> //alert("<?php //echo $res['ID_PERSONNE']; ?>") 
   //donnees.push(<?php //echo $res['ID_PERSONNE']; ?>);

   var variable = { y: <?php echo $resultTabe2[$resultTabe1[$i]]; ?> , x:"<?php echo $resultTabe1[$i]; ?>"};
   donneese1.push(variable);
</script>
 
<?php } ?>

 
<script>//alert(donnees);
$(document).ready(function($) {
function patientsDateAnyChart(){

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.area3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.area(donneese1
    	           	    );

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('Nombre de Patients Par  Date');
		    //chart.labels('label');
		    //chart.labels('x');
		    //chart.xAxis().labels().rotation(-50);

		    // set container id for the chart
		    chart.container('patientsDate');

		    // initiate chart drawing
		    chart.draw();
		});

	}

  patientsDateAnyChart();
});
</script>
</td>
</tr>
</table>
	
    </div>
  	
    
</div>

<script type="text/javascript">

	 $(document).ready(function(){

	$("#nbevo").click(function(){
		$("#AffichageGraphe").html($("#idPatientParDate").html());
		
	});	
	});
</script>

	

</div>

</div>
</div>







<script type="text/javascript">
	 function download(){
		html2canvas(document.getElementById('pSex')).then(function(canvas){
        document.body.appendChild(canvas)

        var imgdata = canvas.toDataURL('image/png')
	 	var doc = new jsPDF()
	 	doc.addImage(imgdata,'PNG',10,20)
	 	doc.save("sample.pdf")
     })

	}


/*	function pdfGen(){
		var doc = new jsPDF();
		doc.fromHTML($('#t').get(0),30,60,{'width':500});
		//doc.innerHTML();
		doc.save('patientsexe.pdf');


	}

/* function pdfGen(idPopupPatientParSexe, title) {
 doc.fromHTML(`<html><head><title>${title}</title></head><body>` + document.getElementById(idPopupPatientParSexe).innerHTML + `</body></html>`);
 doc.save('div.pdf');
}
/*
function pdfGen(idPopupPatientParSexe,
  title) {

  let mywindow = window.open('', 'PRINT', 'height=650,width=900,top=100,left=150');

  mywindow.document.write(`<html><head><title>${title}</title>`);
  mywindow.document.write('</head><body >');
  mywindow.document.write(document.getElementById(idPopupPatientParSexe).innerHTML);
  mywindow.document.write('</body></html>');

  mywindow.document.close(); // necessary for IE >= 10
  //mywindow.focus(); // necessary for IE >= 10*/

 //mywindow.print();
 /// mywindow.close();

// return true;
//}

	
</script>