<style>
#sideBareMenuGaucheinfirmerie{ visibility: hidden; }

#sideBareMenuGaucheinfirmerie{ min-width:200px; max-width: 430px;}
</style>

<script>
$(window).load(function () {

	$('#waitMenuGaucheinfirmerie').toggle(false);
	$('#sideBareMenuGaucheinfirmerie').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheinfirmerie" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>


<ul id="sideBareMenuGaucheinfirmerie">
	
	
	<!-- MENU *** DOSSIER PATIENT*** -->
	<li id="menu_dossier_patient" class="layoutViewMenuGauche"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Dossier patient</span></a> 
	</li>

	<li id="plus_menu_dossier_patient" style="background: #4a5765; " >

	   <div id="menuDesDossierPatient" style="margin-left:30px; height:35px; padding-top:10px; background: yello; border-bottom: solid gray 1px;"><a href="<?php echo $this->basePath()."/consultation/creer-dossier";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_dossier_patient_style" style="font-size:15px; color: white; font-family:Eras Medium ITC; font-style:italic;"> Nouveau </span></a>
	   </div>
	   
	   <div id="menuDesDossierPatient" style="margin-left:30px; height:35px; padding-top:10px; background: gra;"><a href="<?php echo $this->basePath()."/consultation/liste-dossiers-patients";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_liste_dossiers_patients_style" style="font-size:15px; color: white; font-family:Eras Medium ITC; font-style:italic;"> Liste des dossiers </span></a>
	   </div>
	   
	</li>
	
	
	<!-- MENU *** ADMISSION PATIENT*** -->
	<li id="menu_admission_patient" class="layoutViewMenuGauche"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Admission</span></a> 
	</li>

	<li id="plus_menu_admission_patient" style="background: #4a5765; " >

	   <div id="menuDesAdmissionPatient" style="margin-left:30px; height:35px; padding-top:10px; background: yello; border-bottom: solid gray 1px;"><a href="<?php echo $this->basePath()."/consultation/liste-patients-admettre";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_admission_patient_style" style="font-size:15px; color: white; font-family:Eras Medium ITC; font-style:italic;"> Admettre </span></a>
	   </div>
	   
	   <div id="menuDesAdmissionPatient" style="margin-left:30px; height:35px; padding-top:10px; background: gra;"><a href="<?php echo $this->basePath()."/consultation/liste-patients-admis";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_liste_patients_admis_style" style="font-size:15px; color: white; font-family:Eras Medium ITC; font-style:italic;"> Liste patients admis </span></a>
	   </div>
	   
	</li>
	
	
	<!-- MENU *** CONSULTATIONS*** -->
	<li id="menu_consultations" class="layoutViewMenuGauche"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Consultations</span></a> 
	</li>

	<li id="plus_menu_consultations" style="background: #4a5765; " >

	   <div id="menuDesConsultations" style="margin-left:30px; height:35px; padding-top:10px; background: yello; border-bottom: solid gray 1px;"><a href="<?php echo $this->basePath()."/consultation/liste-consultations";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_consultations_style" style="font-size:15px; color: white; font-family:Eras Medium ITC; font-style:italic;"> En cours </span></a>
	   </div>
	   
	   <div id="menuDesConsultations" style="margin-left:30px; height:35px; padding-top:10px; background: gra;"><a href="<?php echo $this->basePath()."/consultation/liste-historique-consultations";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_historique_consultation_style" style="font-size:15px; color: white; font-family:Eras Medium ITC; font-style:italic;"> Historique </span></a>
	   </div>
	   
	</li>
	
	
	
	<!-- MENU *** STATISTIQUES*** -->
	<!-- li id="menu_statistiques"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php // echo $this->basePath().'/images_icons/plus-green1.png'?>' /> Statistiques</span></a> 
	</li>
	
	<li id="plus_menu_statistiques" style="background: #4a5765;" >

	   <div id="menuDesStatistiques" style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php // echo $this->basePath()."/consultation/informations-statistiques";?>" >
	       <img style="margin-left:5px; margin-top: -7px; width: 16px; height: 16px;" src='<?php // echo $this->basePath().'/images_icons/statistics_16.png'?>' />
	       <span id="menu_statistiques_style" style="font-size:15px; color: white; font-family:Times New Roman;">Informations</span></a>
	   </div>
	   
	</li-->
	
	
</ul>


<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];
?>


<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");


//*******************************************************************************************************************************
//*******************************************************************************************************************************
//DOSSIERS PATIENTS -- DOSSIERS PATIENTS
function dep_menu_dossier_patient1(){
	$('#menu_dossier_patient').click(function(){
		$("#menu_dossier_patient").replaceWith("<li id='menu_dossier_patient'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/plus-green1.png' alt='Liste' /> Dossier patient </span></a></li>");
		dep_menu_dossier_patient2();
	    $('#plus_menu_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_dossier_patient2(){
	$('#menu_dossier_patient').click(function(){
		$("#menu_dossier_patient").replaceWith("<li id='menu_dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
		dep_menu_dossier_patient1();
	    $('#plus_menu_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_dossier_patient').toggle(false);
$('#menu_dossier_patient').click(function(){
	$("#menu_dossier_patient").replaceWith("<li id='menu_dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
	dep_menu_dossier_patient1();
    $('#plus_menu_dossier_patient').animate({
 	    height : 'toggle'
    },1000);
    return false;
});


//*******************************************************************************************************************************
//*******************************************************************************************************************************
//ADMISSION -- ADMISSION
function dep_menu_admission_patient1(){
	$('#menu_admission_patient').click(function(){
		$("#menu_admission_patient").replaceWith("<li id='menu_admission_patient'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/plus-green1.png' alt='Liste' /> Admission </span></a></li>");
		dep_menu_admission_patient2();
	    $('#plus_menu_admission_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_admission_patient2(){
	$('#menu_admission_patient').click(function(){
		$("#menu_admission_patient").replaceWith("<li id='menu_admission_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
		dep_menu_admission_patient1();
	    $('#plus_menu_admission_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_admission_patient').toggle(false);
$('#menu_admission_patient').click(function(){
	$("#menu_admission_patient").replaceWith("<li id='menu_admission_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Admission </span></a></li>");
	dep_menu_admission_patient1();
    $('#plus_menu_admission_patient').animate({
        height : 'toggle'
    },1000);
    return false;
});




//*******************************************************************************************************************************
//*******************************************************************************************************************************
//CONSULTATIONS -- CONSULTATIONS
function dep_menu_consultation1(){
	$('#menu_consultations').click(function(){
		$("#menu_consultations").replaceWith("<li id='menu_consultations'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/plus-green1.png' alt='Liste' /> Consultations </span></a></li>");
		dep_menu_consultation2();
	    $('#plus_menu_consultations').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_consultation2(){
	$('#menu_consultations').click(function(){
		$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
		dep_menu_consultation1();
	    $('#plus_menu_consultations').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_consultations').toggle(false);
$('#menu_consultations').click(function(){
	$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
	dep_menu_consultation1();
$('#plus_menu_consultations').animate({
height : 'toggle'
},1000);
return false;
});

//*******************************************************************************************************************************
//*******************************************************************************************************************************
//STATISTIQUES -- STATISTIQUES
function dep_menu_statistiques1(){
	$('#menu_statistiques').click(function(){
		$("#menu_statistiques").replaceWith("<li id='menu_statistiques'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/plus-green1.png' alt='Liste' /> Statistiques </span></a></li>");
		dep_menu_statistiques2();
	    $('#plus_menu_statistiques').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_statistiques2(){
	$('#menu_statistiques').click(function(){
		$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Statistiques </span></a></li>");
		dep_menu_statistiques1();
	    $('#plus_menu_statistiques').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_statistiques').toggle(false);
$('#menu_statistiques').click(function(){
	$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Statistiques </span></a></li>");
	dep_menu_statistiques1();
$('#plus_menu_statistiques').animate({
height : 'toggle'
},1000);
return false;
});

</script>

